### ISSUE TITLE
nativity in Ontario?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1047]
[Originally posted on GoogleCode (id 805) on 2011-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6496

<b>What data are incorrect or missing?</b>

<b>What data are you expecting instead?</b>
Wolffia brasiliensis is not listed for Ontario in FNA nor GRIN, so I wonder if this was a recent introduction that was accidentally recorded as native?

<b>If applicable, please provide an authoritative source.</b>
FNA, GRIN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 13:53Z]

FNA did not report it because the litterature report for the taxon dates from 2005: Thomson,E. R. 2005. Papillate Watermeal,Wolfﬁa brasiliensis,in eastern Ontario:An addition to the ﬂora of Canada. Canadian 
Field-Naturalist 119(1):137-138.
I have added the relevant information to the report and changed the status, however, from native to introduced. http://www.biodiversitylibrary.org/item/109674#page/145/mode/1up

From the report, I deduce it is introduced, but the author does not state it clearly.
