### ISSUE TITLE
question about genus Helianthemum vs. Crocanthemum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1089]
[Originally posted on GoogleCode (id 904) on 2012-01-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/search/?q=Helianthemum

<b>What data are incorrect or missing?</b>
Helianthemum bicknellii Fernald
Helianthemum canadense (L.) Michx.	

<b>What data are you expecting instead?</b>
GRIN, who is usually up to date on nomenclatural changes, 
uses the genus Crocanthemum for the Helianthemum species we have:

Crocanthemum bicknellii (Fernald) Janch.
Crocanthemum canadense (L.) Britton 

<b>If applicable, please provide an authoritative source.</b>
The only reference they cite is:  Weakley, A. S. 2007. Flora of the Carolinas, Virginia, and Georgia, and surrounding areas. (F Carol Virg Georg).  Is this change no longer valid?
See: http://www.herbarium.unc.edu/FloraArchives/WeakleyFlora_2011-May-nav.pdf

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-06 20:04Z]

I have seen no data to support this. I will have to ask Alan Weakley where he got such information. I have not seen the FNA ms of Helianthemum and therefore, do not know whether a specialist would accept the change.
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-09 19:34Z]

Sue
I could not download Weakley's flora for some reason, but I asked him on what he based that. It is based on a 2007 unpublished Ph. D. thesis on the molecular systematics of the group. Bruce Sorrie, the FNA 6 author of the treatment, is making the change in his treatment and he was kind enough to send it to me (it apparently has been lingering in editing prior to regional review, which is why I had yet to see it).
Luc
