### ISSUE TITLE
authority of synonyms - confusion in the databases

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1132]
[Originally posted on GoogleCode (id 951) on 2012-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6092

<b>What data are incorrect or missing?</b>
Lachnanthes tinctoria (Walter) Elliott
Heritiera tinctorum J.F. Gmelin

<b>What data are you expecting instead?</b>
Lachnanthes tinctoria (Walter ex J.F.Gmelin) Elliott
Heritiera tinctorum Walter ex J.F. Gmelin

...or, if water is not recognized, then:
Lachnanthes tinctoria (J.F.Gmelin) Elliott
Heritiera tinctorum J.F. Gmelin

<b>If applicable, please provide an authoritative source.</b>
Tropicos and GRIN use Walter ex J.F.Gmelin, who based his name on Walter's invalid name Anonymos tinctoria Walter.  Although IPNI mentions this fact, they don't give Walter credit, just using J.F.Gmelin as the author of all the combinations.   I'm not sure which is correct.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-19 19:30Z]

Sue

Good catch, but there is a surprize in the conclusion: IPNI is correct. Since the Walter name is invalid, the combination is attributed to Gmelin. I am saying this with some reservation, but I believe it is right. I had other cases like this before and this is what Dr. Gandhi told me.

I fixed what needed to be.

Luc
