### ISSUE TITLE
status of subspecies?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1154]
[Originally posted on GoogleCode (id 973) on 2012-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6528

<b>What data are incorrect or missing?</b>
Lilium canadense Linnaeus subsp. canadense

<b>What data are you expecting instead?</b>
Since subsp. editorum is listed as a synonym, what other subspecies are there for L. canadense?  

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-23 13:57Z]

varieties were not all listed, given that FNA does not list autonymic vars. (they are automatic); added here

There are other varieties of canadense, but syn. of other spp.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-23 14:00Z]

My answer was besides the track. I do not know why we have a subsp. under canadense. i suspect it is due to the fact that Ont. authors recognized (initially at least) subsp. editorum, which is put in syn. by FNA; also, synonymy was not as per FNA for some obscure reason. 

Situation corrected.
