### ISSUE TITLE
status of Callitriche stagnalis in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1288]
[Originally posted on GoogleCode (id 1129) on 2012-02-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7217

<b>What data are incorrect or missing?</b>
Callitriche stagnalis excluded from NF

<b>What data are you expecting instead?</b>
Callitriche stagnalis introduced, probably ephemeral, since we haven't heard ofany further reports.

<b>If applicable, please provide an authoritative source.</b>
In our NF checklist, we have: Callitriche stagnalis is reported in Philbrick et al. (1998) from a 1968 collection: St. John's (UBC}.
But maybe you have more recent info refuting this ID.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-19 21:09Z]

This is touchy: I put "doubtful" because the proper status could not be evaluated at the time. It was not "excluded" (darker gray).

Changed to ephemeral. The date of report would be the key element here: was it more than 50 yrs ago or less than that?

Luc
