### ISSUE TITLE
authorities or ranks of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1348]
[Originally posted on GoogleCode (id 1203) on 2012-03-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7724

<b>What data are incorrect or missing?</b>
a) Hordeum jubatum subsp. intermedium Bowden
b) Hordeum ×intermedium Bowden
c) Hordeum jubatum var. caespitosum (Scribner) Hitchcock

<b>What data are you expecting instead?</b>
a) ?Hordeum jubatum nothosubsp. intermedium Bowden
b) Hordeum ×intermedium Hausskn.
c) Hordeum jubatum [unranked] caespitosum (Scribner) Hitchcock

<b>If applicable, please provide an authoritative source.</b>
a) Tropicos treats subsp. intermedium Bowden as a nothospecies and note that the subsp. was described as a hybrid (Hordeum jubatum ssp. breviaristaum X Hordeum jubatum ssp. jubatum),, replacing the name H. caespitosum Scribn.  IPNI also gives these parents under subsp. intermedium. However, FNA treats it as a subsp. too, but then mentions its supposed hybrid origins.  FNA: &quot;It is sometimes treated as a species, either as H. intermedium Hausskn. or H. ×intermedium Hausskn., the latter reflecting a suspected hybrid origin involving H. jubatum and H. brachyantherum.&quot;. 

I'm not sure whether subsp. or nothosubsp. is correct.

b)Could find no reference to a Hordeum intermedium Bowden, but FNA mentions H. ×intermedium Hausskn. as a syn. in their description of H. jubatum subsp. intermedium (above).  Tropicos lists H. intermedium Hausskn., but provides an unrelated accepted name.  There is also a later homonym by Carleton (misspelled in Tropicos), published in 1916 that = Hordeum vulgare.

c) Tropicos and IPNI list this as unranked, not var.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-05 15:25Z]

a) we do not make distinctions between subspecies and nothosubspecies in order to limit the number of ranks we have to deal with - the level is correct and the x clearly show it as hybrid - this will not be modified

I added one of the parent, but the other not being in the flora could not be added

b) For the time being, I will remove (b) but not add the Hausskn. name as I am uncertain it is based on the same type or hybrid formula

c) IPNI lists it as var., contra your comment - I am keeping this rank currently because VASCAN cannot deal with unranked taxa
