### ISSUE TITLE
common name issue in Symphoricarpos rotundifolius and var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1531]
[Originally posted on GoogleCode (id 1444) on 2012-10-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/25866

<b>What data are incorrect or missing?</b>
missing: roundleaf snowberry
questionable application of: mountain snowberry &amp; Utah snowberry

<b>What data are you expecting instead?</b>
roundleaf snowberry is more appropriate as the accepted common name for the species S. rotundifolia, since the other two common names listed, mountain snowberry &amp; Utah snowberry refer to Symphoricarpos oreophilus and it's synonym S. utahensis.  If these latter two names are included as synonyms, the common names would be fine to include, but why replace the original common name for S. rotundifolius - roundleaf snowberry, with these?

Neither S. oreophilus nor S. utahensis are listed in synonymy here, but S. utahensis auct. non (Rydb.) A.Nelson is included. Utah snowberry should be associated with the taxon S. utahensis or the taxon that now includes S. utahensis as a synonym. The common name mountain snowberry is most often associated wtih S. oreophilus. 

The common names whortle-leaved snowberry and symphorine fausse-airelle seem to be the most appropriate for this taxon: var. vaccinioides, while round-leaved snowberry seems most approprieate for S. rotundifolia.

<b>If applicable, please provide an authoritative source.</b>
common name usage for western Symphoricarpos
&lt;http://www.pnwflowers.com/flower/symphoricarpos-oreophilus&gt; 
&lt;http://science.halleyhosting.com/nature/basin/5petal/honey/symph/snow.htm&gt; 
&lt;http://www.wnmu.edu/academic/nspages/gilaflora/symphoricarpos_rotundifolius.html&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-17 20:11Z]

I am referring this to our vernacular names editors, Marc and Marilyn.

To be followed.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-10-17 20:39Z]

The problem is in part due to the existence of a Symphoricarpos orbiculatus in Ontario, for which the VasCan accepted common names are « round  snowberry » and « symphorine à feuilles rondes ». To avoid any confusion, I used another published French name, « symphorine orbiculaire », as an accepted French name for that species. 
Marilyn, you may want to consider for S. orbiculatus the English name « coralberry », provided in Gray's Manual and also used in the U.K.

I used « symphorine à feuilles ronde » as an accepted French name, at the species level, for S. rotundifolius, and I also kept it as a French synonym for S. orbiculatus, since it is used in an official list in Ontario.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 13:50Z]

completed long ago as tied with issue 1284

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 13:50Z]

completed long ago as tied with issue 1284
