### ISSUE TITLE
misleading common names for Lonicera xbella

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1539]
[Originally posted on GoogleCode (id 1454) on 2012-10-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4229

<b>What data are incorrect or missing?</b>
Fr: chèvrefeuille de Bell 
En: Bell's honeysuckle

<b>What data are you expecting instead?</b>
Fr: chèvrefeuille ? 
En: showy fly honeysuckle or bella honeysuckle

<b>If applicable, please provide an authoritative source.</b>
You can check with Daryshire where he got these names, but this speices is NOT named after a Mr/Ms Bell, or is the flower bell-like. This is the kind of error in common names that should be allowed to linger in botanical references.  
The common name showy fly honeysuckle was used by PLANTS and seems the most appropriate. A few websites use showy bush honeysuckle, but that is also misleading, since these are not Diervillas; I think the use of bush honeysuckle is a common neUS error for non-viney Lonicera species, as I've come across a few people who thought bush honeysuckles are invasives and complained locally when we published our poster on compatible right-of-way plants.  Only introduced shrubby Lonicera spp. are invasive around here, not Diervilla lonicera.  So, to avoid confusion with Diervilla spp., I would prefer to see showy fly honeysuckle used as the accepted English name.  Perhaps Marc can write an appropriate French translation for this? 

A few websites use bella honeysuckle, which is a direct transfer of the epithet that Hermann Zabel published.   I don't know if Zabel gave a reason for his choice of 'bella' in his Gartenflora, published in Berlin (1889), but is seems likely that he would have used a Latin epithet - so bella/bellus could refer to the descriptive beautiful, pretty, etc., referring to the attractive flowers. 

http://plants.usda.gov/java/profile?symbol=LOBE
http://www.uwgb.edu/biodiversity/herbarium/invasive_species/lonxbe01.htm
http://sewisc.org/invasives/invasive-plants/61-bella-honeysuckle
http://www.keiriosity.com/gallery/main.php/v/plants/Caprifoliaceae/Lonicera_X_bella/

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-19 18:09Z]

I am forwarding this to Marc and Marilyn.

The name in Darbyshire, in French, is probably Marc's.

MArc and MArilyn, please address this asap.

Thanks
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-10-29 20:32Z]

I was unable to see the original descriptions to confirm the meaning of "bella", but you must be right, since Fernald (1950) translates the epithet as "pretty", and "bella" would be grammatically incorrect if it referred to a person's name.

Several French equivalents for bellus/a/um exist, but most are not available in this case, because there are different taxa with similar names such as L. superba, L. splendida, and the cultivar 'Elegant'. This left me with the only marginally appropriate "joli" - which happens to be a good translation of Fernald's "pretty".

Thank you for spotting this. I should have noticed this a dozen years ago, when I was checking out the French names for the "Common and Scientific Names" publication.

I kept "chèvrefeuille de Bell" as a synonym, since it is from a published source.

Marc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-10-30 03:24Z]

Thanks very much, Marc.  This sounds great.   Is ch�vrefeuille joli the 
proper way then to write this new name?

Take care, Sue.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-10-30 12:54Z]

Sue,

The correct spelling is « chèvrefeuille joli », i.e. the third letter is an « e » with a grave accent, which seems to have been lost on the way in your comment 3 above.

Marc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-10-30 14:49Z]

Thanks, Marc.   - Sue.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:27Z]

tremendous to get this fixed properly - many thanks!
