### ISSUE TITLE
synonym an illeg. homonym, author of 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1550]
[Originally posted on GoogleCode (id 1466) on 2012-10-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4323

<b>What data are incorrect or missing?</b>
Arenaria pungens Nuttall 
Minuopsis pungens (Nuttall) Mattfeld

<b>What data are you expecting instead?</b>
Arenaria pungens Nuttall (1838), nom. illeg. hom., non Clemente ex Lagasca (1816)
Minuopsis pungens Mattfeld

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI
http://www.tropicos.org/Name/50099318

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 17:22Z]

I also changed the acc rank from subsp. to var., since var. is recognized in FNA, not subsp. (and I cite FNA for the tax concept)

The Mattfeld name is for Minuartia not Minuopsis fide the source you cite
I could not find Minuopsis pungens in TRO or IPNI - need to verify - it is in FNA

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-20 12:24Z]

email to Gandhi, Zarucchi & Rabeler sent 2013-06-20

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-21 12:21Z]

Kanchi's answer:
"Sue and Luc are correct.
Minuopsis pungens" is a typo for Minuartia pungens, which is a nom. illeg., it cannot be used in its stead in FNA."

Thus I am replacing Minuopsis by Minuartia and adding nom. illeg.
