### ISSUE TITLE
typo in genus of synonym; spelling of epithet

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1563]
[Originally posted on GoogleCode (id 1479) on 2012-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4388

<b>What data are incorrect or missing?</b>
Wahlenbergella tayloriae (B.L. Robinson) Rydberg

<b>What data are you expecting instead?</b>
Wahlbergella taylorae (B.L. Robinson) Rydberg

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos
no Wahlenbergella - only Wahlbergella (Caryophyllaceae) and Wahlenbergia (Campanulaceae &amp; Asteraceae).
IPNI has Wahlbergella taylorae Rydb. and mention and basionym, but note the spelling difference - no 'i' here either.
The Panarctic Flora also spells taylorae without an 'i', but they list it under subsp. tenella.  They have different ideas of the subsp. limits than in Vascan.  Now sure which spelling is correct.

&quot;Lychnis taylorae B.L. Rob., Proc. Amer. Acad. Arts 28: 150 (1893). Holotype (GH!): Canada: the Northwest Territories, the Mackenzie River Delta, Pell's River, 15. July 1892, leg. Taylor (see Bocquet 1967: 24). - Melandrium taylorae (B.L. Rob.) Tolm., Trudy Bot. Muz. 24: 267 (1932).&quot;

If taylorae is correct, there are other combinations in this entry that will need to be fixed: Lychnis, Melandrium, Silene. Note that Tropicos includes an annotation that Wahlbergella tayloriae was published as 'Taylorae', so IPNI is going by the original spelling.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-24 18:48Z]

VASCAN lists this sp. under subsp. tenella also - Am I missing something?

Genus corrected

Need advice on sp. spelling - need to check with Kanchi, etc.

**Comment by brouille** [comment]
Response from K. Gandhi, 2018-03-23:
"Now, the IPNI also shows: tayloriae
The problem was: as you know, in Taylor, the ending is “-or”.
In the past, the “-or” ending was considered as equivalent to “-er” ending, which functions as a vowel, and therefore, an “i” was NOT added.
But the Code makes it clear that the “-or” ending is NOT a vowel.  Therefore, we need to add an “i”.
What was published as “taylorae” is corrected to tayloriae."

Most sources had tayloriae
Thus no correction is required.
Luc
