### ISSUE TITLE
invalid hybrid name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1672]
[Originally posted on GoogleCode (id 1599) on 2012-12-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8745

<b>What data are incorrect or missing?</b>
Dryas ×wyssiana Beauverd

<b>What data are you expecting instead?</b>
Dryas ×lewinii Rouleau

<b>If applicable, please provide an authoritative source.</b>
IPNI &amp; Tropicos note that Dryas xwyssiana is an invalid name, as there was no Latin description with the name.  So, it looks like Rouleau's name, Dryas x lewinii should be the accepted name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-14 19:00Z]

Re: Dryas x wyssiana Beauverd 1940

I tried IPNI authors and found these two botanists:
Wyss-Chod. - F. Wyss-Chodat fl. 1927
Wyss. - G.H. Wyssotzky 1899-

Then I looked in IPNI and found that this name is invalid:
IPNI: nom. inval. nom. nud. Latin diagnosis lacking.

BUT, under Remarks, they indicated that this hybrid was named in honor of Edouard Wyss-Dunant (1897-1983), a Swiss physican and alpine enthusiast, one of the first and most successful Swiss attempt to ascend Mt. Everest.  Since this plant was named in 1940, 12 yrs before this expedition, I assume he was honoured because of his many alpine climbs in Switzerland (Matterhorn, etc.); he was also climbing in Greenland in 1938.  Perhaps the type is from Greenland?  Hwr, nothing I've read say's Wyss-Dunant was an amateur botanist.

Maybe you could use Wyss-Dunant's mountain avens;  it's a but cumbersome, but at last it's named for right person.   However, given that D. x wyssiana is invalid, D. x lewinii would be the correct name, so you could use the name Lewin's mountain avens or Lewin's hybrid mountain avens.  Rouleau named this after Spencer Lewin; the type is from Nfld.

I'll send in a note to Luc about the validity of the name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-14 19:20Z]

Marilyn:

oups! Marc did provide a vernacular for this one.

Luc

changed to lewinii as in FNA
