### ISSUE TITLE
question about Nfld. distribution

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1674]
[Originally posted on GoogleCode (id 1604) on 2012-12-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5814
http://data.canadensys.net/vascan/taxon/5812

<b>What data are incorrect or missing?</b>
both varieties - Introduced in Nfld.

<b>What data are you expecting instead?</b>
Are both varieties of Lupinus nootkatensis found in Nfld.?  We only have records of a Clarenville location.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 14:18Z]

Sue

This is indeed an error, and so is it for NS. 
The root of the problem is that the Nfld. list does not provide the var. involved.

Scoggan mentions NS but does not specify which var. is there, though I would suspect var. nootk. given the fact that he mentions fruticosus afterwards.

Would the typical var. be the one present in Nfld.?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 15:23Z]

From Marian Munro, N.S.:
"Neither Roland and Smith nor Erskine specified var. I am thinking it is var. nootkatensis. I have no record of var. fruticosa here.
Regards,Marian"

I am removing both mentions of var. fruticosus from eastern Canada, leaving only var. nootkatensis

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-06-13 15:55Z]

Hi Luc,

John Maunder has photos of thy typical var. from Bay Roberts.

See: 
http://www.digitalnaturalhistory.com/flora_fabaceae_index.htm#lupinusnootkatensisnootkatensis

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 17:09Z]

Sue

That clinches it. I removed the second var. anyway.

Luc
