### ISSUE TITLE
illeg. synonym?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1680]
[Originally posted on GoogleCode (id 1653) on 2013-03-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6616

<b>What data are incorrect or missing?</b>
Althaea hispida Moench

<b>What data are you expecting instead?</b>
?Althaea hispida Moench, nom. illeg.

<b>If applicable, please provide an authoritative source.</b>
The Index Synonymique has Moench's name as a nom. illeg., but this isn't reflected in Tropicos or IPNI, could just be they consider it superfluous, since Linnaeus's name predates it.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 13:51Z]

Sue

I will not add this. I checked the INPN (French index) and they do not mention nom. illeg. - they do place hispida in syn

For the time being, I will keep it as is. I have no direct evidence that the name should be illeg. instead of merely a syn

Unless you have a Code rule that applies?

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-22 15:12Z]

That's fine.  Index Synonymique often lists names as nom. illeg., and 
I'm beginning to think they use this to refer to synonyms that are later 
considered superfluous, which doesn't necessarily make them illegitimate.
