### ISSUE TITLE
range of Betula x utahensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1693]
[Originally posted on GoogleCode (id 1667) on 2013-03-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3717

<b>What data are incorrect or missing?</b>
Range of Betula x utahensis lists only BC and SK 

<b>What data are you expecting instead?</b>
Lepage mentions Dugle's distribution includes BC, AB, YK, + one 1 specimen in SK

<b>If applicable, please provide an authoritative source.</b>
Lepage (1976, p. 232)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 14:34Z]

In the Dugle paper, there is no mention of a specimen for Sask., but the plant is already reported otherwise from there.

Yukon: she states that the documenting specimen is an isotype of Xcommixta, a separate hybrid. I will be prudent here because I am uncertain as to what she means. Does she mean that the specimen was misidentified and not similar to the type of Xcommixta? I will wait before adding Yukon

Luc
