### ISSUE TITLE
2 synonyms - illeg. homonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1714]
[Originally posted on GoogleCode (id 1691) on 2013-04-01]

(This is the template to report a data issue for Vascan. If you want to
report another issue, please change the template above.)

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8725

<b>What data are incorrect or missing?</b>
Crataegus prunifolia (Poiret) Persoon  {1806}
Mespilus prunifolia Poiret  {1798}
Crataegus crus-galli var. prunifolia (Poiret) Torrey &amp; A. Gray

<b>What data are you expecting instead?</b>
Crataegus prunifolia Persoon, nom. illeg. 
{hom., non Baumg. 1790)
Mespilus prunifolia Poiret, nom. illeg. {hom., non Marshall 1785]
Crataegus crus-galli var. prunifolia Torrey &amp; A. Gray

<b>If applicable, please provide an authoritative source.</b>

IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-24 20:46Z]

Crataegus prunifolia Poiret: removed from synonymy in FNA
note that this name replaced Mespilus prunifolia Poir. 

Crataegus crus-galli var. prunifolia Torrey & A. Gray: corrected in the FNA ms by Zarucchi (who updates TROPICOS) to (Poiret) T. & G. - I am asking the nomenclature ed. about this

More synonyms added from FNA ms, new

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 15:56Z]

Crataegus prunifolia (Poiret) Persoon :
FNA9È "The cultivated plant is often called Crataegus prunifolia (Poiret) Persoon in the horticultural literature; this name is invalid because it is a later homonym of C. prunifolia (Marshall) Baumgarten"

nom. illeg. added after Persoon
must we add (Poiret), though? not IPNI, not TRO

Mespilus: nom. illeg. added

nom. editors of FNA consulted

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 17:09Z]

After consultation with K. Ghandi:
Crataegus prunifolia Persoon 
C.crus-galli var. prunifolia Torrey & A. Gray

these names are both substitutes for M. p. Poiret and thus the latter need not be cited in ()

Luc
