### ISSUE TITLE
parents and status of hybrid Crataegus kingsonensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1715]
[Originally posted on GoogleCode (id 1692) on 2013-04-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8687

<b>What data are incorrect or missing?</b>
missing parents of hybrid

<b>What data are you expecting instead?</b>
Gray has possible parents as C. dilatata (now coccinioides)x a species of the Series Brainerdianae), but I can't find any better information than that.

<b>If applicable, please provide an authoritative source.</b>
Gray's manual has this as described from Kingston, ON, so should this taxon be listed as extirpated rather than doubtful? Or will this hybrid not be recognized in FNA?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:01Z]

will have to check - Gray may be incorrect - I hope Phipps has an opinion

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-24 20:51Z]

the taxon is not in the FNA ms - will have to ask Phipps directly

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-14 17:01Z]

Answer from Dr. Phipps:
"I really don’t know anything more about Crataegus kingstonensis than I did in 1980. When I studied Ontario Crataegus, I tried to account for all the names described for the province, which is why it is there. There are over 1200 names in North American Crataegus, some are good species, others are minor variants, while yet others represent putative or (rarely) proven hybrids. Perhaps half, certainly this, have not been seriously studied in recent times."

Phipps 1980: "Only four specimens known, all from the early
part of this century, near Kingston. Perhaps a
transient hybrid. Very close to C. brainerdii Sarg.,
sensu stricto, except for the large fruit. However
the prominent fruiting calyx is reminiscent of series
Pruinosae. Series Brainerdianae."

Since it appears historic and was indigenous, I will put it as extirpated, not excluded. Exclusion would mean there was something wrong with the report or that it was introduced but did not establish.
