### ISSUE TITLE
authority of species; parent of hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1735]
[Originally posted on GoogleCode (id 1712) on 2013-04-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8537
http://data.canadensys.net/vascan/taxon/8568

<b>What data are incorrect or missing?</b>
Coptidium lapponicum (Linnaeus) Gandoger

<b>What data are you expecting instead?</b>
Coptidium lapponicum (Linnaeus) Gandoger ex Rydberg 

<b>If applicable, please provide an authoritative source.</b>
IPNI and GRIN; Tropicos has an incomplete entry for Gandoger

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:09Z]

I have to refer to Gandhi.
L

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 15:36Z]

parents of hybrids added now

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-25 13:48Z]

I did not refer this to Gandhi because upon examination, it is obvious. The TROPICOS entries are both incomplete and therefore not worth consideration. GRIN does its work independantly.
Note that the PanArctic flora is also wrong on this one...

ex Rydberg added

The L. & L. names are isonyms - added to remove ambiguity

The parent name in the hybrid is automatically generated and thus corrected
