### ISSUE TITLE
authorities of 2 synonyms; spelling of 2nd epithet

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1745]
[Originally posted on GoogleCode (id 1722) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8928

<b>What data are incorrect or missing?</b>
Chamaemorus anglica Greene
Chamaemorus norvegica Greene

<b>What data are you expecting instead?</b>
Chamaemorus anglica Clusius ex Greene
Chamaemorus norwegica (Tillandz ex Steudel)Clusius ex Greene
basionym of this name: Morus norwegica Tillandz ex Steudel

<b>If applicable, please provide an authoritative source.</b>
IPNI; Tropcis just has Greene, so you may to check this; 
also they spell the 2nd epithet norvegica; norwegica seems to be the 
original spelling but maybe there's a spelling rule about this?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:41Z]

will have to verify
L

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 20:11Z]

The concept of a plant genus existed before Linnaeus.  Therefore, I have seen the authorship of some generic names cited as "… ex L."(e.g., Lupinus Tourn. ex L.; cited in the Code as an option)

But for our purpose, the concept of binomial nomenclature starts from L.  In this case, Clusius did not use a binomial, but whatever he used was either a polynomial or a phrase name.

Therefore, for C. norwegica and C. anglica, "Clusius ex Greene" is not correct.  Just Greene alone is sufficient.

Also, "norwegica" is the correct epithet spelling.  Seen at: http://www.botanicus.org/title/b11952428

Note: For his C. anglica and C. norwegica, Greene did not provide a description/diagnosis.  Nevertheless, the names are valid, because Greene referred to Clusius's effectively published descriptions for these 2 species names.
