### ISSUE TITLE
basionym author of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1804]
[Originally posted on GoogleCode (id 1802) on 2013-06-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5727

<b>What data are incorrect or missing?</b>
Meiboma rotundifolia Kuntze  {1891)

<b>What data are you expecting instead?</b>
Meiboma rotundifolia (DC.) Kuntze

<b>If applicable, please provide an authoritative source.</b>
IPNI just lists Kuntze as the author, but in synonymy, lists Hedysarum rotundifolium Michaux (1803), which is a nom. illeg. hom., and Desmodium rotundifolium DC. (1825).  Although Kuntze cited the basionym of Michaux,since that one is a homonym, shouldn't deCandolle's 1825 name then become the accepted basionym?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-27 12:47Z]

the generic name is also mispelled : Meibomia

TROPICOS has (Michx.) Kuntze - 

I doubt the DC name could have become the basionym, since TRO has it as (Michx.) DC. - it may have been considered a nom. nov. based on it instead

IPNI may not have considered the () author at the time of data entry

OR there is another issue.

I need to ask, in fact, just in case...

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-11-09 19:13Z]

Because Michaux's name was an illeg. homonym, it can't be used as the basionym of other combinations, so de Candolle's name is the next oldest legitimate name for use with combiations of the epithet rotundifolia.

**Comment by brouille** [comment]
(DC.) Kunze correct fide FNA 11 release - already corrected in VASCAN
