### ISSUE TITLE
questionable synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1815]
[Originally posted on GoogleCode (id 1894) on 2013-10-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6009

<b>What data are incorrect or missing?</b>
Gentiana amarella S. Watson

<b>What data are you expecting instead?</b>
?Gentiana amarella var. stricta (Grisebach) S. Watson

<b>If applicable, please provide an authoritative source.</b>
I can't find any reference to Gentiana amerella S.Watson and the only reference to a S.Watson is the one listed above, but am not sure its a synonym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-17 19:03Z]

The database is correct: it is Gentiana amarella var. stricta

However, there was an error in entry and instead of var., the entry was labeled as species, which cuts off the varietal name and creates a series of errors

I am requesting the database manager to switch from sp. to var. (I cannot change this field once it is set).

I corrected the authority, however.
