### ISSUE TITLE
missing English vernacular for Desmodium dillenii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1845]
[Originally posted on GoogleCode (id 1939) on 2013-11-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9824

<b>What data are incorrect or missing?</b>
missing English vernacular

<b>What data are you expecting instead?</b>
Dillenius' tick-trefoil

<b>If applicable, please provide an authoritative source.</b>
http://wisplants.uwsp.edu/scripts/detail.asp?SpCode=DESPANvDIL

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 19:35Z]

Marilyn

A suggestion of missing EN vernacular. OK with you?

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 20:15Z]

Many thanks again. Agree with name, also added 'Dillen's tick-trefoil' as also very much in use

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-01-25 15:00Z]

Luc & Marilyn: I don't think it's a good idea to include vernaculars based on misspellings, such as 'Dillen's tick-trefoil'.  Dillenius was his name, not Dillen; why perpetuate spelling errors based on incorrect information?

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-25 18:51Z]

I really believe leaving reference to "Dillen's" as a synonym is ok - as it's very much in use, plus as named in Britton and Brown. The accepted name does indicate the correct spelling.
Trying to be consistent in approach, as previous comments received on names have suggested other additions (such as different spellings)to be included due to usage.
