### ISSUE TITLE
parents of hybrid: Mentha xdumetorum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1869]
[Originally posted on GoogleCode (id 1965) on 2013-11-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6407

<b>What data are incorrect or missing?</b>
Mentha spicata x M. aquatica

<b>What data are you expecting instead?</b>
Mentha aquatica x M. longifolia

<b>If applicable, please provide an authoritative source.</b>
GRIN, MBG: http://www.tropicos.org/Name/17604061
also: http://link.springer.com/article/10.1007%2FBF00036774#page-1

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 14:08Z]

Sue

The error came from Morton and from the fact that in NA, M. longifolia has been mistakenly used for plants of M. spicata

I will not be able to add longifolia as the second parent because it is not in the flora. This is one limitation of VASCAN that I cannot go around. I made a note in the database itself, however, but these are not public.

Luc
