### ISSUE TITLE
Stachys pilosa documented for Newfoundland

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#192]
[Originally posted on GoogleCode (id 1651) on 2013-03-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6471

<b>What data are incorrect or missing?</b>
Stachys pilosa is not mapped for Newfoundland

<b>What data are you expecting instead?</b>
Stachys pilosa mapped for Newfoundland

<b>If applicable, please provide an authoritative source.</b>
2 annotated specimens returned fom DAO to MT, MT-33661 &amp; MT-30789 in MT database, documented in file &lt;MT12-03 reçu de DAO.pdf&gt; cc'd to Luc Brouillet 15fe2013

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 14:05Z]

The reason why is this comment in Meades et al. 2000: [Mulligan et al. (1983, 1989) report that Stachys palustris is a hexaploid European weed that is introduced in our area.  Stachys pilosa, native to Quebec and westward, is absent from the rest of eastern Canada.]

I guess the specimens change this. The problem is: is it native?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-25 13:34Z]

G. Mulligan annotated two MT specimens in 2012 as S. pilosa
I checked the specimens and they are clearly pilosa and from native habitat, one from the Burin Pen., collected by Etcheberry, the other from Terra Nova NP collected by ... Charest and Brouillet! Son of a gun. The habitat is native, apparently. A range extension.

Status : native

Although both are databased, they do not appear to have been published in Canadensys under this name, so the entry may not have been corrected in our database.
