### ISSUE TITLE
missing vernaculars for Limonium platyphyllum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1940]
[Originally posted on GoogleCode (id 2055) on 2014-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/27910

<b>What data are incorrect or missing?</b>
English vernacular missing

<b>What data are you expecting instead?</b>
suggestions:
English vernacular: broadleaf statice, German statice
French vernacular: statice vivace

<b>If applicable, please provide an authoritative source.</b>
http://apps.rhs.org.uk/plantselector/plant?plantid=1169
GRIN has this species listed under the name Limonium gerberi 1991, a later name for Limonium latifolium (Sm.) Kuntze 1891, an illeg. homonym.
http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?402065

I've seen Limonium latifolium listed as a synonym of both L. gerberi and L. platyphyllum, but is L. gerberi also a syn of L.platyphyllum, or was the name L. latifolium misapplied to L. gerberi?

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-01-23 17:48Z]

Delete the suggestion of German statice for Limonium platyphyllum; this is used for Gioniolimon tataricum (in Dan's dB), but sometimes (mis)applied to L. platyphyllum.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-24 18:17Z]

Marc et Marilyn

Pourriez vous svp évaluer et entrer les noms vernaculaires suggérés par Sue

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-25 18:44Z]

name already in use in UK as 'florist's sea lavender'. the term 'broad-leaved' is already in use with L. auriculae-ursifolium.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-01-28 18:19Z]

Is Limonium latifolium (Sm.) Kuntze here considered a synonym of L. platyphyllum? (See https://data.nbn.org.uk/Taxa/NHMSYS0020110562) If so, maybe it should be mentioned in VasCan, because there are French names available for L. latifolium.

"statice vivace" cannot be used as a recommended (i.e. accepted)  French name, because we have chosen "limonium" as a French generic for other species. Also, "statice vivace" is used for Goniolimon tataricum and for other species of Limonium. It could be entered as a French synonym, but I cannot find a source for this.

I entered 2 French names for the L. platyphyllum, but these might not be valid if L. platyphyllum is considered distinct from L. latifolium. Please advise.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-04 15:38Z]

English names are finished. Are the French names finished?
Then this issue can be indicated as 'done' ;)
