### ISSUE TITLE
wqstion about subspecies

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1943]
[Originally posted on GoogleCode (id 2058) on 2014-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8052

<b>What data are incorrect or missing?</b>
no subspecies are listed, yet I don't see Navarretia intertexta subsp. propinqua in synonymy

<b>What data are you expecting instead?</b>
Are this subsp. and subsp. intertexta [recognised in the US-PLANTS) now   synonyms of the species, or has subsp. propinqua been moved to another taxon/rank? Both subsp. are reported from BC in PLANTS.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-24 16:49Z]

Sue

I cannot answer this because the FNA ms, which would address such issues, is not in yet. Such taxonomic decisions require the specialist, and PLANTS is based on Kartesz's taxonomy, not always authoritative.

I accept the issue, but cannot close it.

Luc

**Comment by brouille** [comment]
This issue has been resolved with release of FNA draft treatment. The subspp are treated as separate species. See VASCAN latest releases.
LB
