### ISSUE TITLE
presence of Viola maccabeiana in BC

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1964]
[Originally posted on GoogleCode (id 2102) on 2014-02-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9494

<b>What data are incorrect or missing?</b>
status of Viola maccabeiana in BC

<b>What data are you expecting instead?</b>
Rare Plants of BC lists Viola maccabeiana as endemic to BC and lists some herbaria with specimens.  
If these records are valid, this species should be listed as native in BC.

<b>If applicable, please provide an authoritative source.</b>
http://victoria.tc.ca/Environment/Botany/rare.html
scroll down to V`s
Name: Viola maccabeiana M.S. Baker
Herbaria: DAO, UBC, UC, V
Ref.:  Baker 1940, Hamet-Ahti 1965
Range: Central to se BC
BC range: Bugaboo Mtns.; Quesnel Highland; Shuswap Highland; Thompson
Plateau; Rocky Mtn. Trench (Wells Gray Park, Mara Meadows, Canal
Flats, Kinbaket Lake, Vaseaux Lake, Kelowna, Inadianpoint Lake)
Biogeocl.: SS, CA, IF
Habitat: Moist Places, meadows, along streams
Rare status: R1
BC CDC status: none
Note:  Endemic to BC

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-04 19:51Z]

Sue

You are drawing your data from all kinds of sources. I cannot always follow all this.

eFlora, an electronic rendition of the Ill. Flora of BC, had the name under synonymy of V. nephrophylla and the FNA ms was not even listing the taxon - I do not know whether or not the taxon is recognized now - that it be aknowledged by the rare plants of BC does not give it taxonomic status - it could be due to eagerness to have taxa listed

I will have to wait for a more authoritative source, not for the record (I had it as ? in BC)not because of specimens, but because of taxonomy.

We will wait a bit here.
Luc

**Comment by brouille** [comment]
Viola maccabeiana is apparently a syn of  V. nephrophylla, which is reported for BC
eFlora of BC still report the species, but with 2 syn. in V. nephrophylla - this apparently is incorrect
VASCAN is now in accordance with FNA 6
Luc
