### ISSUE TITLE
French vernacular for Botrychium alaskense

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#200]
[Originally posted on GoogleCode (id 787) on 2011-10-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
Botrychium alaskense

<b>What data are incorrect or missing?</b>
French vernacular (botryche petit-lutin) is also used for Botrychium mormo

<b>What data are you expecting instead?</b>
a specific FR vernacular for this species (for Marc to review/provide)

<b>If applicable, please provide an authoritative source.</b>

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-04 21:22Z]

I deleted « botryche petit-lutin » as a French name for B. alaskense, and I entered the new name « botryche d'Alaska ».

This is a recurring problem when a new species is added to the database. It seems that the vernacular names of another species, presumably used as a template, get copied into the new entry.

I assumed that this problem is now solved with the use of Google issue, but there may be a few similar cases remaining among species that were recently added to VasCan.

If you can produce a list of recent additions (year 2011 might be a good option), I can check the French names for that set of taxa.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-10-05 09:25Z]

many thanks Marc. Yes hopefully we are notified when these switches occur so we can re-examine the vernaculars if still suitable. But I'm pretty sure we are being notified via this google issue tool.
Please also let me know of anything for the English vernaculars needs fixing, although I know there are many to be fixed yet for monocots and dicots. I finished my review of the gymnosperms and ferns/fern allies.
Marilyn
