### ISSUE TITLE
question of parentage of Solidago x bartramiana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2048]
[Originally posted on GoogleCode (id 2279) on 2014-08-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3503?lang=en

<b>What data are incorrect or missing?</b>
Solidago canadensis Linnaeus var. canadensis x Solidago uliginosa

<b>What data are you expecting instead?</b>
Solidago fallax (Fernald) Semple x Solidago uliginosa

<b>If applicable, please provide an authoritative source.</b>
Since S. canadensis (all subsp.) do not occur in NL, one of the parents of this cross should probably be S. fallax, as this hybrid is known only from Nfld.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-11 15:44Z]

I need to check with Semple

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-20 19:54Z]

Semple email 2014-08-20
I have seen the HT at GH and an ITs at CAN and NY of Solidago
bartramiana.  My educated guess is that it is Solidago brendiae × S.
uliginosa.  Both are present in Grand Falls, NF and both are diploid.
The inflorescence is appropriate for a such a hybrid.  Mid and upper
leaves are weakly triple-nerved.  The lowest stem leaves present have
petioles that are not sheathing the stem like the usual basal leaves of
all subsect. Maritimae but they have bases that are wider than you would
get in subsect. Triplinervae.  In subsect. Maritimae, Solidago
gracillima looses the sheathing leaf trait very quickly so even the
lower stem leaves are not sheathing.  I grew the several collections of
the species to make observations on the rosette leaves and they are
clasping.  Thus, the clasping trait could be hard to see in flowering
material of S. ×bartramiana because there are no rosettes present on the
type material and the lower leaves have all dropped off by flowering.
The material I have seen of S. bartramiana is all much shorter than S.
brendiae and in the range of mid size S. uliginosa.  The type habit is
talus and ledges below the falls, so I assume lots of water for a "bog"
habitat genome and not enough soil for the plants to get big.
Cheers,
John

I need a source to cite now
LB
