### ISSUE TITLE
Status of Hieracium robinsonii in insular NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2084]
[Originally posted on GoogleCode (id 2325) on 2014-10-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3233

<b>What data are incorrect or missing?</b>
Status in inslular Nfld. - native in VASCAN

<b>What data are you expecting instead?</b>
We had this listed as historically present, with last collections listed from 1911.  You list it as native in Nfld., and John Maunder has 2+ sets of images in his digital flora of pix that are awaiting confirmation of ID.  Have you verified the ID from these pix?
http://www.digitalnaturalhistory.com/genus_hieracium_index.htm#hieraciumrobinsonii

The pix he includes from NB (Sean Blaney's pix) have very different leaves.  Details of other features too small to compare.

<b>If applicable, please provide an authoritative source.</b>
Bouchard et al. 1991 (Rare Plants of NL) and our Checklist

**Comment by brouille** [comment]
Sue

I just saw a photocopy of the photo of an isotype at NY of H. robinsonii : it comes from Holyrood, Nfld. The holotype is probably at GH. I will check this again. But André, Stu and I did not collect is at Holyrood, where the whole place was colonized by H. lachenalii (aka vulgatum). It is possible that the taxon is now eradicated from the type location. I do not know whether others have found it since the early 1900 collection.

I would consider it eradicated (NOT excluded) from NL.

Luc
