### ISSUE TITLE
2 synonyms are later isonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2118]
[Originally posted on GoogleCode (id 2462) on 2015-01-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3686?lang=en

<b>What data are incorrect or missing?</b>
Betula alba var. cordifolia (Regel) Fernald
Betula papyrifera var. cordifolia (Regel) Fernald

<b>What data are you expecting instead?</b>
Betula alba var. cordifolia (Regel) Regel (1868), non (Regel) Fernald (1902)
Betula papyrifera var. cordifolia (Regel) Regel (1865), non (Regel) Fernald

<b>If applicable, please provide an authoritative source.</b>
IPNI, Fernald's 1902 publication, and Tropicos(Tropicos erroneously repeats one of the pubications for both of Regel's var. combinations).

Regel actually made the combination as Betula alba subsp. papyrifera (beta) cordifolia, but this is interpreted as equivalent to B.alba var. cordifolia, making Fernald's name a later isonym.

I haven't seen Regel's publications, but these names appear in several databases.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-30 21:26Z]

I added nom. illeg. to the Fernald names, because they have been used, and added new syn's with Regel. Also, it keeps the numbers used by VASCAN intact in this case

FNA was contacted to indicate this issue, which predates KAnchi's time as our nomenclature editor. It will get corrected to the Regel name, I guess

Luc
