### ISSUE TITLE
additional synonym for Betula michauxii?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2120]
[Originally posted on GoogleCode (id 2465) on 2015-01-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3690?lang=en

<b>What data are incorrect or missing?</b>
Betula nana L. var. flabelifolia Hooker - reported by Hook from Newfoundland and Labrador

<b>What data are you expecting instead?</b>
Should this taxon be listed as a synonym of Betula michauxii, as none of the combinations of Betula nana occur in the province, unless they're synonyms of Betula mixhauxii?

<b>If applicable, please provide an authoritative source.</b>
IPNI mentions this taxa from NL

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-26 18:29Z]

i cannot simply add a synonym on a hunch. I must know where it fits.

There is also the danger of modifying the taxon concept (probably not in this case)

More research required before adding

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2015-02-26 18:36Z]

You're right, it does need checking.

**Comment by brouille** [comment]
@sjmeades 
This was a bit difficult to address because the TROPICOS entry [I cannot cite it because the server is experiencing difficulties currently] cites the wrong flora.
IPNI has : Fl. Bor.-Amer. (Hooker) 2(10): 157. 1838
I checked in BHL and found the description at 
http://www.biodiversitylibrary.org/item/13840#page/159/mode/1up
The description indeed is very suggestive of B. michauxii (except for the female bract, described as more deeply lobed while it is entire - this may be an interpretation error) - it is from Nfld. and provided by Cormack!
Then I got lucky[er]: There was a mini-symposium on Betula michauxii that was published in the Memoirs of the Montreal Botanical Garden:
http://www2.ville.montreal.qc.ca/jardin/archives/rousseau/publi/Betula_Michauxii_a_brief_symposium.pdf
In the paper 2 by Rousseau & Raymond, they state:
"It could be added that Betula nana L. [beta] flabellifolia Hooker (in ...) probably belongs here, and would be the oldest varietal name".
I could not find an image of the type in the K database. I may have to ask someone there to scan it.
However, I believe the information is sufficient to include this name as a synonym. 
But validating with the type would be best.
Luc
