### ISSUE TITLE
question of acceptance in FNA

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2159]
[Originally posted on GoogleCode (id 2566) on 2015-03-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8961

<b>What data are incorrect or missing?</b>
Sibbaldia tridentata (Aiton) Paule &amp; Soják is accepted in VASCAN

<b>What data are you expecting instead?</b>
Sibbaldiopsis tridentata (Aiton) Rydberg is accepted in FNA (9:300)

<b>If applicable, please provide an authoritative source.</b>
FNA; is this an oversight, or do you accept Sibbaldia tridentata over Sibbaldiopsis tridentata?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-02 20:54Z]

This is a case of the author not wanting to change her treatment while knowing that Sibbaldiopsis should be in Sibbaldia as per phylogenetic data. I checked the paper.

In the case of some authors (notably Ertter), I chose to go with phylogenies instead of opinions, monophyly vs paraphyly.

No change required. This had been considered.
LB

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2015-04-02 21:05Z]

I'm happy staying with Sibbaldia.  Thanks for the clarification.
