### ISSUE TITLE
Checklist for Ontario does not include  Authorities, Vernacular Names or synonyms

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2176]
[Originally posted on GoogleCode (id 553) on 2011-06-27 by daleadbeater]

I am trying to build a checklist for Ontario to use as the authority for the preparation of an inventory for a municipality.  The Ontario checklist is limited to species names.  I would like more of the data that is linked to the species.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-06-27 15:40Z by luc.brouillet]

Peter:

I just checked how to do what Dale is asking and I am stymied.

Is there a way to build a checklist including vernaculars and synonyms? I just realized we have not included this among the options under display criteria.

If we do not have such a feature, we may need to add it...

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-07-21 16:11Z]

You are right: accepted vernacular names (French and English) are missing from the text file downloads. We will add these once our new developer is here.

But synonym vernacular names or synonyms cannot be added to the flat text files, since those could range from 0 to 30+, creating 0-30+ extra columns. However, all that information can be downloaded in the Darwin Core archive format, which allows to share relational information.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-08-01 20:07Z]

Add accepted french and english vernacular names to text file download. Add it after "Scientific name" column. Name of the columns should be "vernacular fr" and "vernacular en".

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-11-22 19:40Z]

This issue was closed by revision r218.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-11-22 19:42Z]

Vernacular fr and Vernacular en are now included in the text file. This will be live Monday Nov 26h 2012. Sorry for the delay.
