### ISSUE TITLE
Bromus pumpellianus

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2255]
[Originally posted on GoogleCode (id 1422) on 2012-09-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Bromus%20pumpellianus

<b>What data are incorrect or missing?</b>

likely native at some Ontario sites (M.J. Oldham)

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-01 13:36Z]

I changed the status in VASCAN from introduced to native. Such cases where status is mixed are always difficult since original data are often unclear.

Thanks for the update. It will appear after the next compilation, within the next month or so.

Luc
