### ISSUE TITLE
Cyperus engelmannii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2270]
[Originally posted on GoogleCode (id 1870) on 2013-09-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/15521?lang=en

<b>What data are incorrect or missing?</b>

see spreadsheet 4

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:07Z]

Mike

I can see why you would want to follow this, particularly as FNA states: "Cyperus odoratus is an exceedingly variable pantropical and warm-temperate species. Numerous segregates have been named, some of which may deserve recognition when the species is studied in detail worldwide."

WCSP at Kew does not recognize the taxon for the world list (but this is not always a definite answer)

But Mears & Libby 1995 should have done a quantitative study to prove their point. It is still based on classic taxonomy.

I read Reznicek and Voss:"Very often growing with C. odoratus. Despite the general tendency to recognize C. engelmannii as part of a variable C. odoratus, we tentatively agree with Mears & Libby (1995) that North American plants at least seem clearly distinct."
I am troubled: it is often co-occurring; and their agreement is tentative

I wished someone would do a proper study.

I am keeping as is for the moment, until new analyses based on data (morphometry) are produced. I know that one opinion is worth another, but since we try to follow FNA until uncontrovertible data prove it wrong, I have to keep the taxon as it for the moment. I hope it will come soon

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 22:27Z]

That's fine.  Apparently the two taxa are quite distinct in the north (and seem so in Ontario) but less so further south (Tucker's treatments of Cyperus in Mexico and/or Costa Rica).
