### ISSUE TITLE
Arisaema triphyllum subsp. pusillum in Ontario?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2287]
[Originally posted on GoogleCode (id 2371) on 2015-01-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/2673

<b>What data are incorrect or missing?</b>

Do you have a source for the occurrence of Arisaema triphyllum subsp. pusillum in Ontario?  None is provided in VASCAN and I can't find a reference to its occurrence in the province.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
FOIBIS mentions it as a syn of subsp. triphyllum, but also as a separate entity, but without data

Due to the difficulty of recognizing the subspp. most authors appear to treat triphyllum in the broad sense, without distinguishing the subspp. However, note this:
"Arisaema triphyllum is generally considered to be a single species with three subspecies – the diploids A. t. stewardsonii and A. t. pusillum and the tetraploid A. t. triphyllum, which originated as a hybrid of the first two. However, the three are reproductively isolated in the wild, which would argue for treating them as species. The main reason for considering them subspecies seems to be the difficulty in distinguishing them, especially based on herbarium specimens" (wikipedia)

citing : http://www.theprimrosepath.com/Featured_Plants/Arisaema_triphyllum/triphyllumcomplex.htm
"The Flora of North America gives a taxonomic key to distinguish A. triphyllum, A. pusillum, and A. stewardsonii. All three have the same basic arrangement of a single stem bearing one or two compound leaves with a single inflorescence on the stem at the base of the leaf or between the leaves.

We have not found much difficulty in distinguishing populations of the Arisaema triphyllum group in the field. In our general area, southwestern Pennsylvania and northern West Virginia, A. triphyllum and A. pusillum are common. We have found A. stewardsonii only in Tucker Co., West Virginia, where it occurs in swamps in the Canaan Valley. The species can be characterized:
Arisaema triphyllum is generally more robust. The foliage is usually glaucous (silvery green) below. The spathe (the cone-shaped "pulpit") is contrastingly striped white and green and often with purple-brown and is not vertically ridged. There is a relatively wide, slightly rolled flange on the horizontal edges of the spathe. The spadix ("jack") is club-shaped, thicker near the top than in the middle.
Arisaema pusillum is generally a little smaller. The foliage is green below. The spathe is striped only subtly, and the flange is less wide and less rolled. The spadix is cylindrical or slightly more slender at the top. Where populations are mixed, A. pusillum is usually in wetter areas at the bottom of the slope, A. triphyllum up on the slopes.
Arisaema stewardsonii is also a little smaller and with foliage that is green below. The spathe is heavily ridged, so much so that the overhanging hood cannot be reflexed to expose its inside without damaging it. The side flanges of the spathe are narrow and not rolled. The spadix is cylindrical."
Thus, this author tends to recognize 3 species (let alone subsp.)

I believe the lack of report is more based on the difficulty of distinguishing the entities in the herbarium than for a lack of biological distinctions (2 are 2n, pusillum and stewardsonii, while triphyllum is allopolyploid 4n)

I am not sure what is best to do: merging them all would appear to merge potential taxa into a single entity that may not be biologicall OK

Luc
