### ISSUE TITLE
Geum fragarioides

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2303]
[Originally posted on GoogleCode (id 2392) on 2015-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8990?lang=en

<b>What data are incorrect or missing?</b>

No scientific name authority (source) provided and treated in Waldsteinia in FNA Vol. 9.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-22 13:31Z]

Mike

Phipps INSISTED to treat Waldsteinia apart in FNA, despite all phylogenetic data and the opinion of the specialist of the group. I decided NOT to follow FNA in this instance, despite its recency, because I consider this poor taxonomy.

I have to find a source indeed for the name, preferably electronic.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:12Z]

Added Smedmark 2006 as source
