### ISSUE TITLE
Crataegus x kingstonensis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2305]
[Originally posted on GoogleCode (id 2399) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8687

<b>What data are incorrect or missing?</b>

Not fully treated in FNA Vol. 9, but mentioned on page 522.  Name in FNA is not given as a hybrid (i.e. C. kingstonensis not C. x kingstonensis as in VASCAN) but stated to be &quot;perhaps a hybrid of ser. Anomalae X C. pruinosa&quot;.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 19:56Z]

Dr. Phipps has always puzzled me with these rare entities that he treats as species then mention as potential hybrids. If it is extinct, there may be more reason to believe it was a very transient hybrid and not a stable species. I will keep the x as he was not very consistent (I know because it was a contentious subject).

Should I put it as extirpated in Ontario and leave it as this?

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 21:34Z]

Given the difficulty with Crataegus identification I personally would be cautious about calling it extirpated (likely no one has actually tried to refind it).  We use the rank of SH for such cases (historic, i.e. no recent records, but not enough search effort to be confident it is extirpated).

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-09 21:38Z]

Good enough for me. Had to ask.
Luc

Le 2015-02-09 16:34, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-10 19:17Z]

It is truly worth trying to relocate a HYBRID? If they disappeared, too
bad: they were just a transient phenomenon. Phipps has been dealing with
scores of these and could not get around to stating they had been
ephemeral in evolutionary time. However important the phenomenon in
evolution of plants.

Luc

Le 2015-02-09 16:34, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by brouille** [comment]
This is an old email from Phipps, dated 2013-06-14, related to this taxon:
" I really don’t know anything more about Crataegus kingstonensis than I did in 1980. When I studied Ontario Crataegus, I tried to account for all the names described for the province, which is why it is there. There are over 1200 names in North American Crataegus, some are good species, others are minor variants, while yet others represent putative or (rarely) proven hybrids. Perhaps half, certainly this, have not been seriously studied in recent times."

Status changed to doubtful to reflect SH of Mike Oldham
Luc
