### ISSUE TITLE
check French vernacular for Crataegus chrysocarpa var. piperi

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#232]
[Originally posted on GoogleCode (id 2369) on 2014-12-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8660?lang=en

<b>What data are incorrect or missing?</b>
I think the FR vernacular 'aubépine du Columbia' is more suitable with Crataegus douglasii as per listed synonymy.
I'm working on the EN vernaculars as well but will double check when FNA is published.

<b>What data are you expecting instead?</b>
suggestion - aubépine de Piper

<b>If applicable, please provide an authoritative source.</b>

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-01-02 20:58Z]

You are totally right. Thank you for spotting this. I made the correction. Similarly, you may want to check the adequacy of the name « western hawthorn » when used for C. douglasii, since C. columbiana var. occidentalis is a synonym of C. macracantha var. occidentalis, not C. douglasii.

I happen to be working on the Rosaceae just now, but I still have to look at the Crataegus.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-01-03 14:57Z]

Many thanks Marc! Happy New Year!
