### ISSUE TITLE
Arethusa bulbosa in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#233]
[Originally posted on GoogleCode (id 2370) on 2015-01-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6835?lang=en

<b>What data are incorrect or missing?</b>
first record of Arethusa bulbosa in NWT at Scotty Creek, Fort Simpson.

<b>What data are you expecting instead?</b>
add NWT

<b>If applicable, please provide an authoritative source.</b>
field work by Wilfrid Laurier Univ students, 2 photo records only. 
I'll try to attach links. 
If not, then can be found at 'PhytoImages.siu.edu' - search at Locality 'Scotty Creek' then choose 'Orchidaceae' at bottom of page.

Image at PhytoImages.siu.edu 

Image at PhytoImages.siu.edu

**Comment by brouille** [comment]
@manions 
Marilyn
I added the ref. to the image as the source. But that is a very poor way of referencing records because nothing ensures the stability (continued existence) of this website or photo. A herbarium specimen would have been much better. But people do not do specimens any longer (and have not enough botanical culture to realize when they see something new).
Luc
