### ISSUE TITLE
Poa saltuensis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2363]
http://data.canadensys.net/vascan/taxon/7902

"old pasture bluegrass" seems an inappropriate name for a native woodland grass (I can't imagine it growing in a pasture).  We use "Drooping Bluegrass" for P. saltuensis and subsp. saltuensis and "Weak Bluegrass" for subsp. languida.

MIKE OLDHAM

**Comment by brouille** [comment]
@manions 
Marilyn, could you please handle this issue?
Luc

**Comment by manions** [comment]
Hi Mike
Many thanks for alerting the name-habitat issue on this taxon. I've spent many hours on this one and other Poa now. It seems many repeats of the 'old pasture bluegrass' name based upon Fernald 1950, although 'saltuensis' means 'belonging to the forest', and Fernald's original article in Rhodora 20 indicates the species as woodlands and open clearings.
Since there are many Poa (alsodes, nemoralis, sylvestris, saltuensis) with woods/woodland/forest in vernacular usage, I've had to do some review to choose the best suitable names (hopefully ok now!). 
Poa saltuensis subsp. languida has been changed to 'weak bluegrass' following Fernald 1950, that then resulted in Poa infirma changed to 'European weak bluegrass' as it also was known as 'weak bluegrass'.
Poa saltuensis subsp. saltuensis has been changed to 'open woodland bluegrass', which I've used as its common name to avoid confusion with P. nemoralis and P. sylvestris. I think that is the best name for the taxon as 'drooping' also is in usage for subsp. languida.
Marilyn
