### ISSUE TITLE
re: Range of Elatine minima in Labrador.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2386]
Re: http://data.canadensys.net/vascan/taxon/5463?lang=en

When John Maunder was reviewing the new checklist, he stated that he had withdrawn his claim of having Elatine minima from Labrador, so suggested that I remove 'L' from the range.  I assume this means that his ID was incorrect.  But I'm not sure what information the range of E. minima in VASCAN is based, but if you have no other reports of E. minima from Labrador, I'll remove it from the new NL checklist.

**Comment by brouille** [comment]
There was no other source for E. minima in VASCAN since the source was Meades et al. 2000.
MT had no specimen.
I always am weary of unverified specimens/observations, yet John often insists. I will be stricter in future.
I have no source for excluding the species. There will have to be a list of exclusions with reason for it in the next list [preferably, with new det. of misidentified reports if at all possible]
Luc
