### ISSUE TITLE
Dryopteris filix-mas subsp. brittonii in Labrador?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2392]
re: http://data.canadensys.net/vascan/taxon/5392?lang=en

Do you have any Labrador reports of Dryopteris filix-mas subsp. brittonii?  VASCAM shows a Labrador distribution,

**Comment by brouille** [comment]
Sue

If you look at the list view, you will see that we have specimens at MT documenting the presence of this subspecies.

We recently reviewed and databased Dryopteris, which is why we were able to determine the subspecies present in different regions of Canada. All eastern material is this subsp. and we did have a specimen. It will be published soon in Canadensys, with a major update on MT data.

Luc

De : sjmeades <notifications@github.com<mailto:notifications@github.com>>
R�pondre � : Canadensys/vascan-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 16 juin 2015 17:18
� : Canadensys/vascan-data <vascan-data@noreply.github.com<mailto:vascan-data@noreply.github.com>>
Objet : [vascan-data] Dryopteris filix-mas subsp. brittonii in Labrador? (#2392)

re: http://data.canadensys.net/vascan/taxon/5392?lang=en

Do you have any Labrador reports of Dryopteris filix-mas subsp. brittonii? VASCAM shows a Labrador distribution,

�

**Comment by sjmeades** [comment]
Received the ACCDC data for NL yesterday and there is a specimen of D. f-m subsp. brittonii from seLab., which Claudia collected.
