### ISSUE TITLE
Castilleja minor var. exilis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2477]
@manions 
According to the FNA draft of Castilleja, Castilleja minor is represented in BC not by var. minor as previously reported (eg, Kickenberg), but by var. exilis. Some of the English vernaculars listed for minor in fact apply better to this var. exilis.
The French vernacular is questionable.

Please review names and keep only pertinent ones, adding sources.
Thanks
Luc

I will send the file by email since attaching files does not work. L.

**Comment by MFavreau** [comment]
French name added. I normally would have used a translation of the Latin epithet « exilis », but there is already another taxon with a similar name. Also, I avoided « annuelle », since several species are annual in the East : one was even named « annua » in the past. So, I used a French translation of « alcali paintbrush « which seems quite specific to this variety.

**Comment by manions** [comment]
finished review of English vernaculars
