### ISSUE TITLE
Tanacetum binnatum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2505]
http://data.canadensys.net/vascan/taxon/3600?lang=en

I don't understand how Tanacetum huronense var. floccosum can be listed as an infraspecific taxon of T. bipinnatum, when T. huronense is listed as a synonym of T. bipinnatum subsp. huronense.

MIKE OLDHAM

**Comment by MFavreau** [comment]
This issue was raised several years ago. Var. floccosum is of conservation concern, but the required new combination does not yet exist.
The following rationale is provided as a comment in the database :
"var. floccosum S1 SK fide COSEWIC list
combination needs to be made under bipinnatum: TAnacetum bipinnatum (Linnaeus) Schultz-Bipontinus subsp. huronense (Nuttall) Breitung var. floccosum (Raup) <<auth.>>"
