### ISSUE TITLE
Trillium erectum - VASCAN ne tient pas compte des deux variétés décrites dans FNA

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2585]
Salut

FNA mentionne deux variétés pour le Québec.
Trillium erectum var. album (Michaux) Pursh

Trillium erectum var. erectum

Fred

**Comment by brouille** [comment]
Fred
FNA dit: "Variety album differs from var. erectum mainly just in petal color, and probably should be reduced to the rank of forma. Many other colors occur sporadically in otherwise typically maroon to purple populations, most frequently a soft pale yellow, but also white with a pink overlay, or paler forms of reddish maroon. Only some of these other forms seem to have been named. This is probably to the good, since some are forms in the true sense but others may represent interspecific hybrids (F. W. Case and G. L. Burrows 1962)." 
Cela ne fait pas une var. très forte si l'auteur dit que ce pourrait être une forme...

Luc
