### ISSUE TITLE
Potentilla tikhomirovii still considered a hybrid?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#267]
[Originally posted on GoogleCode (id 2507) on 2015-03-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9777?lang=en

<b>What data are incorrect or missing?</b>
Currently listed as a hybrid Potentilla ×tikhomirovii, on VASCAN.
FNA volume 9, although mentioned in the text as an assumed hybrid species, lists as Potentilla tikhomirovii. 

<b>What data are you expecting instead?</b>
Just double checking on how this should be listed as a hybrid or not (as working on flora for NT &amp; NU jurisdictions). Thanks

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 18:00Z]

B. Ertter, author of Potentilla, was loath to use the x symbol when hybrids were assumed. However, evidence pointing in this direction, I prefer to indicate it in VASCAN
If ever it is proven otherwise, it will be changed. For now, it is the most likely status (otherwise it would be a good sp...)
Luc
