### ISSUE TITLE
use of vars. in Origanum vulgare

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2679]
http://data.canadensys.net/vascan/taxon/30491?lang=en

Is there a draft FNA treatment for Origanum?  I'm looking for more information (a published reference) for the use of varieties in this species.  It seems that in Europe authors use subspecies, following the revision by Ietswaart (1980; O. vulgare portion attached).  The combination O. vulgare ssp. hirtum is credited to (Link) Ietswaart, but the combination O. vulgare var. hirtum to Visiani.  Should the VASCAN entries be at the subsp. rather than var. level?

Mike Oldham
[Origanum vulgare FROM Ietswaart 1980_A taxonomic revision of the genus Origanum (Labiatae).pdf](https://github.com/Canadensys/vascan-data/files/1112086/Origanum.vulgare.FROM.Ietswaart.1980_A.taxonomic.revision.of.the.genus.Origanum.Labiatae.pdf)

**Comment by brouille** [comment]
Origanum attached. It was sent to reviewers in February. I am not sure all names are dealt with there.

Luc

De : MichaelOldham <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : jeudi 29 juin 2017 08:54
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] use of vars. in Origanum vulgare (#2679)


http://data.canadensys.net/vascan/taxon/30491?lang=en

Is there a draft FNA treatment for Origanum? I'm looking for more information (a published reference) for the use of varieties in this species. It seems that in Europe authors use subspecies, following the revision by Ietswaart (1980; O. vulgare portion attached). The combination O. vulgare ssp. hirtum is credited to (Link) Ietswaart, but the combination O. vulgare var. hirtum to Visiani. Should the VASCAN entries be at the subsp. rather than var. level?

Mike Oldham
Origanum vulgare FROM Ietswaart 1980_A taxonomic revision of the genus Origanum (Labiatae).pdf<https://github.com/Canadensys/vascan-data/files/1112086/Origanum.vulgare.FROM.Ietswaart.1980_A.taxonomic.revision.of.the.genus.Origanum.Labiatae.pdf>

**Comment by MichaelOldham** [comment]
Thanks Luc,

The FNA draft uses subspecies in Origanum vulgare, VASCAN uses varieties (presumably VASCAN should be changed to subspecies).

mike

**Comment by brouille** [comment]
I am not sure why I have a discrepancy. Usually I take heed. Thanks for mentioning it.

We are in the process of publishing a new version of VASCAN. It should be out next week.

Luc

De : MichaelOldham <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : jeudi 29 juin 2017 09:23
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Luc Brouillet <luc.brouillet@umontreal.ca>, Comment <comment@noreply.github.com>
Objet : Re: [Canadensys/vascan-data] use of vars. in Origanum vulgare (#2679)

Thanks Luc,

The FNA draft uses subspecies in Origanum vulgare, VASCAN uses varieties (presumably VASCAN should be changed to subspecies).

mike

**Comment by brouille** [comment]
Status of names corrected.

Actually, the FNA ms had the wrong authorities for subsp. hirtum (isonym). So I corrected this too.

Thanks
Luc
