### ISSUE TITLE
Oenothera filiformis introduced in ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2711]
http://data.canadensys.net/vascan/taxon/6798?lang=en

We consider O. filiformis to be introduced in Ontario, since (a) the only two recent records of which I am aware are from highly disturbed sites along railway tracks; (b) southern Ontario is well outside the core range of this western species (e.g. range map in Raven & Gregory 1972; considered "probably only adventive" in Michigan); and (c) the only other Ontario record is a collection from Scarborough in 1905 (DAO), cited in Raven & Gregory (1972) who state "Probably introduced at most stations outside of its main area of distribution".

Mike Oldham
[Raven & Gregory 1972_A REVISION OF THE GENUS GAURA (ONAGRACEAE).pdf](https://github.com/Canadensys/vascan-data/files/1428082/Raven.Gregory.1972_A.REVISION.OF.THE.GENUS.GAURA.ONAGRACEAE.pdf)

**Comment by brouille** [comment]
Thanks Mike
Luc

De : MichaelOldham <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : lundi 30 octobre 2017 13:12
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Oenothera filiformis introduced in ON (#2711)


http://data.canadensys.net/vascan/taxon/6798?lang=en

We consider O. filiformis to be introduced in Ontario, since (a) the only two recent records of which I am aware are from highly disturbed sites along railway tracks; (b) southern Ontario is well outside the core range of this western species (e.g. range map in Raven & Gregory 1972; considered "probably only adventive" in Michigan); and (c) the only other Ontario record is a collection from Scarborough in 1905 (DAO), cited in Raven & Gregory (1972) who state "Probably introduced at most stations outside of its main area of distribution".

Mike Oldham
Raven & Gregory 1972_A REVISION OF THE GENUS GAURA (ONAGRACEAE).pdf<https://github.com/Canadensys/vascan-data/files/1428082/Raven.Gregory.1972_A.REVISION.OF.THE.GENUS.GAURA.ONAGRACEAE.pdf>

**Comment by brouille** [comment]
status modified to introduced
