### ISSUE TITLE
recognition of Andersonglossum boreale

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2712]
http://data.canadensys.net/vascan/taxon/29172

Suggest recognizing Andersonglossum boreale as a species distinct from A. virginianum following Jimenez-Mejias et al. (2017; attached).  Only A. boreale occurs in Canada.

Mike Oldham
[Jimenez-Mejias et al 2017_The study of online digitized specimens revalidates Andersonglossum boreale as a species different from A. virginianum (Boraginaceae).pdf](https://github.com/Canadensys/vascan-data/files/1479578/Jimenez-Mejias.et.al.2017_The.study.of.online.digitized.specimens.revalidates.Andersonglossum.boreale.as.a.species.different.from.A.virginianum.Boraginaceae.pdf)

**Comment by brouille** [comment]
I was kind of expecting this. It had not been done in the FNA draft by Cohen.

Only need to sort out the accepted English vernacular.

**Comment by brouille** [comment]
Marilyn and Marc

Please check that the vernacular names for Andersonglossum boreale are correct. I removed Cynoglosse de Virginie, which is not appropriate since the species is not in Canada, only boreale (virginiana var. boreale for some).
However, the current English vernacular appears to apply to A. virginianum and not boreale. If so, please erase and switch to appropriate name.

Thanks
Luc

**Comment by MFavreau** [comment]
J'ai inscrit le nom français correct, qui est « cynoglosse boréale ». Attention, le nom générique français est féminin, contrairement à ce qu'écrivait Marie-Victorin. C'est important, surtout vis-à-vis la cynoglosse officinale (nom accepté pour le Cynoglossum officinale).
Marc

**Comment by manions** [comment]
English vernaculars reviewed and adjusted. Many thanks for the article
