### ISSUE TITLE
common names for Artemisia campestris subsp. canadensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2756]
Re: http://data.canadensys.net/vascan/taxon/10719

There are no common names listed for this subspecies.  FNA lists armoise du Canada and the French common name, but no English name.  The Govt. of Maine lists Canadian wormwood as the English common name.  See: http://www.maine.gov/dacf/mnap/features/artcan.htm

**Comment by MFavreau** [comment]
French name added.

The French name « armoise du Canada » has been in use at least since Provancher (1862). It was used in Marie-Victorin's Flore Laurentienne and also in an earlier version of VasCan, under _Artemisia canadensis_. It was probably accidentally dropped when the taxon became a subspecies of _A. campestris_.

Marc

**Comment by manions** [comment]
Many thanks, English vernacular 'Canada wormwood' added as used by Britton and Brown
