### ISSUE TITLE
re: Family Comandraceae for Geocaulon and Comandra

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2765]
FNA includes former Santalaceae genera Comandra and Geocaulon in the family Comandraceae.  Is this change going to be made in VASCAN or is there a reason why this change in family names will not be followed.

**Comment by brouille** [comment]
I am perfectly aware of this issue. The problem is that "specialists" of the group like to divide it, while APG IV prefers to maintain larger families.
Same can be found in Boraginaceae and (unfortunately) Caprifoliaceae.
I am somewhat waiting for the dust to settle and people come to an understanding.
Unfoortunately, I cannot easily reflect both positions in VASCAN.
Luc
