### ISSUE TITLE
common name and new range for Hypericum maculatum subsp. obtusiuscula

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2767]
Re: http://data.canadensys.net/vascan/taxon/6156

This subsp. of Hypericum is the true identify of the plant found in Newfoundland and misIDed as Hypericum punctatum.   Maunder had it listed in the Digital Flora as Hypericum punctatum, first collected from Stephenville Crossing in 1996.  I found more populations in the Gallants area of wNL and Pasadena in 2015-16, then Sean Blaney found more pops in the Pinchgut area of NL, not far from Gallants.  Sean was the first person to pick up the incorrect ID, thanks to Robson's publication of the FNA treatment of Hypericum, and determine that the NL plants were actually this subsp. of H. maculatum.  This species did not appear in Fernald's Gray's Manual, hence the previous misIDs.  The most noticeable difference in the plants is the square stem of H. maculatum subsp. obtusiusculum, compared to terete stems in H. punctatum.  So, plants previously reported as H. punctatum actually refer to H. maculatum subsp. obtusiusculum.  it's obviously introduced and well-established in wNL, and seems to be quickly spreading along the west coast, likely through ATV tracks, where we've found it.

This plant is also found in BC, and appear in the E-Flora BC website under the common name 'spotted St. John's-wort, which is a much more appropriate common name than the new name coined for VASCAN: western European St. John's-wort.  In addition to the BC Flora, the USDA Plants database and EOL refer to this as the spotted St. John's-wort.  This common name was already well established in the lit, so there's no reason to make up a new common name.  I suggest using spotted St. John's-wort as the accepted name for Hypericum maculatum subsp. obtusiusculum.

**Comment by MFavreau** [comment]
I will leave it to Marilyn to decide on the most appropriate English name for H. maculatum subsp. obtusiusculum, but I would like to make a general comment on the choice of vernaculars for infraspecific taxa. Our policy is that the vernacular accepted in VasCan for a given species can also be applied to the autonymous (or typical) infraspecific taxa of that species, but not to other subspecies and/or varieties. So, since "spotted St.John's-wort" is the accepted English common name for the species H. maculatum, it would be preferable to select a different one for subsp. obtusiusculum, even though the latter seems to be the only infraspecific taxon of H. maculatum so far reported from Canada, This may seem strange to have two accepted names for what amounts to be the same material in a Canadian perspective, but this avoids future problems in the case subsp. maculatum would turn out to be also occurring in Canada.

Marc

**Comment by manions** [comment]
Thanks Marc. Yes there is some issues to use the name of 'spotted' for this species, as that common name is also used as an accepted name for H. punctatum (such as used in FNA which has wide usage/acceptance). Although we do consider vernaculars used by Canadian sources carefully in each case, we review vernaculars used for all the taxa within a genus. Also as Marc has explained, we strive for unique vernaculars for each taxa, including infraspecific taxa.
