### ISSUE TITLE
Hieracium lachenalii subsp. cruentifolium in ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2855]
http://data.canadensys.net/vascan/taxon/30729?lang=en

Newmaster et al. (1998) is given as the source for Hieracium lachenalii subsp. cruentifolium being in Ontario as well as the source for H. vulgatum being in Ontario.  Newmaster et al. list H. vulgatum, with H. lachenalii as a synonym and no mention of subsp. cruentifolium.  Euro+Med is listed as the taxonomic authority for Hieracium lachenalii subsp. cruentifolium but FNA is listed as the taxonomic authority for H. vulgatum (FNA states that "The correct name for the species here called Hieracium vulgatum may be H. lachenallii").  Euro+Med lists H. vulgatum as a nom. confus. and a synonym of H. lachenalii subsp. cruentifolium.  Most references dealing with the Ontario flora (e.g. Morton and Venn 1990, Newmaster et al. 1998) and adjacent areas (E.g. Flora Novae-Angliae, Michigan Field Manual, Catalogue of NY State plants) consider H. vulgatum a synonym of H. lachenalii.  I question that we know which subsp. of H. lachenalii occurs in Ontario. Euro+Med lists more than 100 accepted subsp. of H. lachenalii and subsp. cruentifolium has a quite restricted distribution in Europe and seems unlikely to be the only subsp. in Canada.  Given the uncertainty around the taxonomy and identification of this group, maybe it would be safest to just list the species, unless there are confirmed records to the subsp. level for some provinces (not for Ontario as far as I know).

**Comment by brouille** [comment]
Hieracium vulgatum is removed and transferred as a syn of H. lachenalii subsp. cruentifolium. Vulgatum was left behind by mistake, which has been underlined by others as well.

I will be using the subsp. because not only E+M list it as taxonomic parent, but also the Cichorieae Database 
http://cichorieae.e-taxonomy.net/portal/cdm_dataportal/taxon/573cf2a0-7ae0-4b26-b597-868eafedb740
which I use as a major taxonomic ref for this group. The distribution of this taxon from northern and central Europe is not so small, reachjing from Norway to perhaps northern Italy (or the Alps at least). At the present time, I will follow the accepted wisdom
Luc
