### ISSUE TITLE
Acer pseudoplatanus French vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2914]
https://data.canadensys.net/vascan/taxon/9211?lang=en

Should French vernacular be érable sycamore rather than érable sycomore?

**Comment by MFavreau** [comment]
No, « érable sycomore » is correctly spelled. It is one of several common names used in France, and the one recommended by TelaBotanica.

 

See  <https://www.tela-botanica.org/bdtfx-nn-210-ethnobotanique> https://www.tela-botanica.org/bdtfx-nn-210-ethnobotanique 

 

Marc

 

De : MichaelOldham <notifications@github.com> 
Envoyé : 23 septembre 2019 11:25
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Acer pseudoplatanus French vernacular (#2914)

 

https://data.canadensys.net/vascan/taxon/9211?lang=en

Should French vernacular be érable sycamore rather than érable sycomore?
