### ISSUE TITLE
Oxalis stricta common names

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2921]
https://data.canadensys.net/vascan/taxon/7083?lang=en

FNA Vol. 12 (2016) considers Oxalis stricta to be native to North America and introduced in Europe, so the English and French names European wood-sorrel and oxalide d'Europe are perhaps misleading. FNA uses the English name upright yellow wood-sorrel.

**Comment by brouille** [comment]
Marc and Marilyn
Please address the issue above.
Luc

**Comment by MFavreau** [comment]
There are other similar cases. One familiar example is Canada Thistle, which is an introduced species in North America.

Of course, "Canada thistle" and "oxalide d'Europe" are misnomers, but I believe they should remain as accepted vernaculars, because they are the standard names used by CFIA and on herbicide labels.

Marc
