### ISSUE TITLE
Inula racemosa in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2942]
Known in Ontario from several recent iNaturalist reports from the Greater Toronto Area (e.g. https://inaturalist.ca/observations/31227832,  https://inaturalist.ca/observations/31475059) and one from Ottawa (https://inaturalist.ca/observations/39556063). Not sure if there are any Ontario specimens in herbaria (likely filed as I. helenium) or if iNaturalist reports are sufficient documentation for VASCAN (I have accepted this species for Ontario in our database). I will attempt to obtain herbarium voucher material this coming field season.

**Comment by brouille** [comment]
Mike

I am adding the species to VASCAN, but so far I have not accepted iNaturalist as documentation because of diverse issues (permanence of records, etc.). I will leave the source blank for now, until either a specimen is deposited at a herbarium or a publication appears. I will put the iNat documentation in my remark block, which is not public, however.
Note that the taxon is known from Québec, documented at MT.
Luc
