### ISSUE TITLE
consider Lamiastrum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2976]
https://data.canadensys.net/vascan/taxon/32270

FNA draft treatment (P.W. Ball 2009) treats this as Lamiastrum, as do some other recent regional treatments (e.g. https://michiganflora.net/species.aspx?id=1551).

**Comment by brouille** [comment]
Bendiksby et al 2011 (a specialist of the group) show L. galeobdolon as sister to all remaining Lamium in ITS phylogeny, but whithin Lamium in cpDNA phylogeny. Here is what he states about the status of this taxon with respect to Lamium: "Thus, L. galeobdolon may deserve to be circumscribed in a sepa- rate genus on the account of being very distinct. In spite of this, we hesitate to place L. galeobdolon in a separate genus (Lamiastrum) because monophyly of the rest of Lamium is not supported by the cpDNA data (Fig. 3). Monotypic taxa such as Lamiastrum may also be considered redundant in classifi- cation. The large clade of Lamium including L. galeobdolon is strongly supported by molecular data (Figs. 1–3; see also Bendiksby & al., 2011a) and may be supported by the presence of an elaiosome at the base of the nutlets (Gams, 1927; Bouman & Meeuse, 1992)"
WCSP includes Lamiastrum within Lamium. Peter Ball and Fl. Michigan have both followed tradition. I decided to follow the word of experts in the group in this case
Luc
