### ISSUE TITLE
Aphyllon franciscanum - addition au Canada (B.C.)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3034]
https://www.ingentaconnect.com/content/aspt/sb/pre-prints/content-2000076;jsessionid=2nsohwgj5vs4c.x-ic-live-03

**Comment by brouille** [comment]
Le lien conduit à une page indiquant: Content Not Found This content is no longer hosted
Je n'ai pas de lien à Sys Bot
Luc

**Comment by FredCoursol** [comment]
https://doi.org/10.1600/036364421X16231782047479

La revue papier est disponible à la bibliothèque du jardin

**Comment by brouille** [comment]
The taxon Aphyllon franciscanum has been added to VASCAN.

Marilyn & Marc:
French and English vernacular names are required. The authors of the paper did not provide any.
Luc

**Comment by MFavreau** [comment]
French name added.

Marilyn : the Schneider & Benton (2021) paper provides a comment which may be of interest to you for selecting the English name 👍 
Etymology—Achey (1933) does not describe her choice of name, but it appears to refer to the type locality of the San Francisco Bay Area (Mount Tamalpais, California) or the underlying geology, which has been referred to as “Franciscan” in various senses since the 1800s (Berkland et al. 1972).

Marc

**Comment by manions** [comment]
Many thanks, English vernacular added
