### ISSUE TITLE
Castilleja parviflora - introduction au Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3044]
Salut

Gisèle Lamoureux avait trouvé cette espèce dans le parc de la Mauricie.
Je reçois de nombreuses demandes d'identifications de cette plante qui se retrouve encore dans le parc.
Jacques Labrecque a contacté Jacques Pleau qui confirme et qui nous a envoyé des photos de la plante.
J'envoie un message à Annie Saint-Louis de l'herbier Louis-Marie afin de confirmer la présence d'un spécimen

**Comment by brouille** [comment]
Il faudra identifier la variété svp - je présume var. parviflora
Lamoureux avait laissé de nombreux spécimens du parc à MT. As-tu vérifié ici?
Luc

**Comment by FredCoursol** [comment]
QFA a un spécimen identifié à C. boréales par Camille Gervais du parc de la Mauricie.
J’ai des photos. On pourrait peut-être l’identifier

Envoyé de mon iPhone

Le 28 janv. 2022 à 13:50, brouille ***@***.***> a écrit :

﻿

Il faudra identifier la variété svp - je présume var. parviflora
Lamoureux avait laissé de nombreux spécimens du parc à MT. As-tu vérifié ici?
Luc

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanadensys%2Fvascan-data%2Fissues%2F3044%23issuecomment-1024511330&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gNPuzl8H9xA7chG2BnduyPT2N5x7ldp3wOcYqRUMrCQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZVLSIPPHSXJCMZIDFXYBTUYLQQVANCNFSM5MFPN2UA&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q3r8XqD47YEz%2BVElfJ70WQjSEPAZkUtYEOTmvV2x2q8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yb%2F3WpxD%2FqxtbKeydYWA5VlC83FCYjSN2yCoK%2FDFpF8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iCfObGoxlBGjDin5vI6cINrlHqG6vhApeIRGy2RRxBg%3D&reserved=0>.

**Comment by brouille** [comment]
Tu veux dire C. parviflora?

Je peux aussi vérifier MT lundi.

Luc

De : FredCoursol ***@***.***>
Répondre à : Canadensys/vascan-data ***@***.***>
Date : vendredi 28 janvier 2022 à 14:08
À : Canadensys/vascan-data ***@***.***>
Cc : Luc Brouillet ***@***.***>, Comment ***@***.***>
Objet : Re: [Canadensys/vascan-data] Castilleja parviflora - introduction au Québec (Issue #3044)

QFA a un spécimen identifié à C. boréales par Camille Gervais du parc de la Mauricie.
J’ai des photos. On pourrait peut-être l’identifier

Envoyé de mon iPhone

Le 28 janv. 2022 à 13:50, brouille ***@***.***> a écrit :



Il faudra identifier la variété svp - je présume var. parviflora
Lamoureux avait laissé de nombreux spécimens du parc à MT. As-tu vérifié ici?
Luc

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanadensys%2Fvascan-data%2Fissues%2F3044%23issuecomment-1024511330&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gNPuzl8H9xA7chG2BnduyPT2N5x7ldp3wOcYqRUMrCQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZVLSIPPHSXJCMZIDFXYBTUYLQQVANCNFSM5MFPN2UA&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q3r8XqD47YEz%2BVElfJ70WQjSEPAZkUtYEOTmvV2x2q8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yb%2F3WpxD%2FqxtbKeydYWA5VlC83FCYjSN2yCoK%2FDFpF8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C58d31a27d67b4e0b0e9108d9e28f1b61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789926559278525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iCfObGoxlBGjDin5vI6cINrlHqG6vhApeIRGy2RRxBg%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanadensys%2Fvascan-data%2Fissues%2F3044%23issuecomment-1024523865&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3f454710cebc4f10d3ab08d9e2918b36%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637789937000011192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UMJGNoIKL2FgMIHvPZBchEDRpr3FdlWHQq08%2F0HTTzY%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZV5Y7S2SQE5YRV64ACXR3UYLSSDANCNFSM5MFPN2UA&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3f454710cebc4f10d3ab08d9e2918b36%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637789937000011192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eA3Nh%2F8S6h%2BQb6pKTx7RGjeIn6dPVJsIKhgcp%2FNAlrs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3f454710cebc4f10d3ab08d9e2918b36%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637789937000011192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iGXENh6HdCd3bs5h%2FqJOt2WEEBVbrRWkfHIo3pekm68%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C3f454710cebc4f10d3ab08d9e2918b36%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637789937000011192%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FVwfc%2F6WaNGml7I9T%2BIvZxBsADCXHpb9E432a6JKeK4%3D&reserved=0>.

**Comment by brouille** [comment]
identification faite par Jacques Labrecque à un autre Castilleja
LB
