### ISSUE TITLE
question on Origanum heracleoticum

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3047]
Would Origanum heracleoticum be the synonym of Origanum vulgare var. hirtum?
The former isn't mentioned in Arthur Tucker's draft FNA treatment.
Thanks
Marilyn

**Comment by manions** [comment]
here is the link to the specimen labelled as O. heracleoticum
https://herbweb.botany.ubc.ca/herbarium/details.php?Database=vwsp&AccessionNo=V224970

**Comment by brouille** [comment]
Origanum heracleoticum is synonym of Origanum vulgare subsp. viridulum (Martrin-Donos) Nyman according to all sources I consulted: powo.science.kew.org/taxon/urn:lsid:ipni.org:names:453267-1
http://ww2.bgbm.org/EuroPlusMed/PTaxonDetail.asp?NameId=143963&PTRefFk=8000000
inpn.mnhn.fr/espece/cd_nom/138443
I presume that Tucker did not take it into account because, though it appears to be cultivated, it does not establish in the flora, as eFLora states: https://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Origanum%20heracleoticum
I am updating the taxonomy in VASCAN to Origanum vulgare subsp. viridulum
Luc

**Comment by brouille** [comment]
Marilyn et Marc:
An English vernacular name would be required. eFlora BC uses one (with I believe a typo): Greek oregeno
Is not marjoram a general vernacular for the herb? Or oregano or origano at least...

Thanks Luc

The French  vernacular from tela-botanica seems less suitable than an alternate proposed in INPN: origan vert (both are mentioned)  inpn.mnhn.fr/espece/cd_nom/138443

**Comment by MFavreau** [comment]
D'accord. J'ai inscrit le nom origan vert comme nom accepté et conservé l'autre nom comme synonyme.

Marc

**Comment by manions** [comment]
Many thanks, English vernacular added from Kintzios's review of the genus. BC 's name not used as that's properly used for subsp. hirtum.
