### ISSUE TITLE
missing basionym in synonym of Viola selkirkii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3065]
_Viola umbrosa_ Fr. should be _Viola umbrosa_ (Wahlenb.) Fr.
the basionym is: _Viola hirta_ L. var. _umbrosa_ Wahlenb.

Checked in Plants of the world online: https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:869455-1
and GBIF.

**Comment by brouille** [comment]
Sue

I am puzzled because GBIF gives Viola umbrosa Fr. but does list hirta var. umbrosa Wahl. I could not find the combination in TROPICOS or IPNI either, nor the var. name for that matter. And I am wary of POWO since they often have erroneous author information. 

At issue is the possibility that var. umbrosa Wahl. and umbrosa Fr. were not based on the same type, though I do not know this as I do not have access to the protologue. I will have to investigate further.

Luc

**Comment by sjmeades** [comment]
OK.  Great.  I didn’t have access to Wahlenberg’s publication, so couldn’t confirm.   The page below is from Botaniska Notiser (via Google books) and lists Viola umbrosa (Wahlenb.) Fr., but again, you’ll definitely need to see Wahlenberg’s original publication; Novit. Fl. Suec. Alt: 271 (1828), to determine which is correct.  Thanks, Sue.

 

And GBIF has V. hirta var. umbrosa Wahlenb. as a synonym of V. selkirkii, but keeps Viola umbrosa Fr. separate.

**Comment by brouille** [comment]
I made the change finally substantiated by POWO and worldplants
LB
