### ISSUE TITLE
Accept infraspecific for Carex rostrata Stokes: Carex rostrata var. ambigens Fernald

### ISSUE THREAD

**Issue by cmrobillard** [Canadensys/vascan-data#3078]
I noticed PWO recognizes infraspecifics for Carex rostrata whereas VASCAN currently does not. When I looked up what the infraspecifics were, it looks like the one that isn't the automatic name is a Quebec/NB species:  Carex rostrata var. ambigens Fernald.

https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:47018-2
https://www.ipni.org/n/47018-2

Perhaps this taxon is well reviewed and understood by Canadensys to not be a valid variety. If so, could this be added as a synonym of C. rostrata?

Please let me know VASCAN's decision on this when it is reached so that I can incorporate it into our collection. 

Thank you!

**Comment by brouille** [comment]
Carex rostrata var. ambigens is considered a synonym of Carex rostrata as it is deemed insufficiently distinct. None of the conservation agencies that would be concerned by this taxon (CDPNQ and ACCDC) list it. It was not listed in FNA, which explains why it was missed in VASCAN initially. USDA PLANTS list the name ambigens as a synonym of Carex rostrata. POWO recognized the name because it had been included in a world list of Carex, but no critical examination of its status was done by them.
I will add the name in synonymy.
Thanks for having drawn my attention to this missing name in VASCAN
Luc Brouillet
