### ISSUE TITLE
Agastache rugosa présent au Québec

### ISSUE THREAD

**Issue by elbourret** [Canadensys/vascan-data#3152]
On a un spécimen d'une étudiante de Floristique (2024) qui démontre que Agastache xrugosa est présent à l'état spontané au Québec.

Maria Bourque no. 1 (MT)

**Comment by brouille** [comment]
Selon le ms FNA, A. rugosa est une bonne espèce d'origine asiatique et non un hybride et est mentionné en disussion de foeniculum (pas traité):
"Agastache foeniculum is widely cultivated.  According to various commercial websites, hybrids between this species and the Asian A. rugosa are available, as is the pure species A. rugosa.  Specimens in the New England Wild Flower Society Herbarium were collected in Worcester County, Massachusetts, as escapes; similar specimens have been collected in Maine (A. Haines, pers. comm.).  These are tentatively identified as hybrids because they have petioles more or less canescent, leaf blades in the size range of A. foeniculum but with attenuate apices (atypical of A. foeniculum), an intermediate abaxial surface covering, and inflorescences in the length range of A. foeniculum (4--10 cm).  Agastache rugosa is characterized by petioles canescent, leaf blades mostly 8--15 cm with distinctly attenuate apices, abaxial surfaces glabrous or with hairs 0.1--0.3 mm scattered primarily along the veins, and inflorescences 7--22 cm.  These plants are reported to be reproducing by seed and persisting, but whether they are adventive has not been established.  J. E. Vogelmann (1985) found that, in his small sample, experimental hybrids between these two species were sterile; this suggests instead that these escapes may be depauperate or atypical plants of A. rugosa.  Further clarification is needed."
Même chose ds POWO, etc.
Luc

**Comment by brouille** [comment]
Marilyn and Marc
Vernacular names are needed for this species. None were provided in FNA (only mentioned in discussion).
Je ne sais si INPN aura ce taxon.
Luc

**Comment by MFavreau** [comment]
French name added. C'était dans le site de l'INPN!

**Comment by manions** [comment]
English names added
