### ISSUE TITLE
nouveau taxon ajouté: Adiantum aleuticum var. subpumilum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#357]
[Originally posted on GoogleCode (id 1058) on 2012-02-06]

Suite à des informations transmises par Marilyn, j'ai ajouté le taxon suivant à VASCAN: 
Adiantum aleuticum var. subpumilum

svp, veuillez ajouter les vernaculaires français et anglais

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-06 22:20Z]

I find it difficult to find an adequate common name, because the epithet subpumilum seems to have been transfered from the older A. pedatum subsp. subpumilum, where it probably served to distinguish the taxon from typical A. pedatum sensu lato. So it may not adequately describe actual differences with the modern A. aleuticum var. aleuticum within the narrower concept of A. aleuticum.

Marilyn, could you send me the info you sent to Luc for the addition of the taxon to VasCan, and/or give me your opinion on a proper common name for this taxon?

Thank you.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-08 22:22Z]

French name entered. adiante nain Thank you Marilyn.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-09 12:14Z]

completed
