### ISSUE TITLE
Change rang of hybrid

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#362]
[Originally posted on GoogleCode (id 1195) on 2012-02-29]

http://data.canadensys.net/vascan/taxon/8175
Polygonum fowleri subsp. fowleri x P. fowleri subsp. hudsonianum
The hybrid is between two subspp. of the same sp., yet we gave it the rank of species, which prevents me from placing it under its proper parent, P. fowleri

Rang should be subspecies, not species

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:12Z]

There are 3 such taxa in the database:
http://data.canadensys.net/vascan/taxon/8175
http://data.canadensys.net/vascan/taxon/7490
http://data.canadensys.net/vascan/taxon/4748

They are now recorded as:
uninomial: Polygonum
binomial: fowleri
trinomial: fowleri x Polygonum fowleri subsp. hudsonianum
rank: subspecies

We will have to verify the name building formula reacts.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:25Z]

Saved via editor and name seems to be build correctly for the most part, but there are some errors. I'm not sure these are specific for these 3 special hybrids or for hybrids in general:
- calnamauthor (and calnamehtmlauthor) has space at the end:
"Calamagrostis canadensis var. canadensis × Calamagrostis canadensis var. pickeringii "

- calnamehtml puts the whole hybrid combination as italic:
<em>Calamagrostis canadensis</em> var. <em>canadensis × Calamagrostis canadensis var. pickeringii</em>

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:26Z]

And they are missing specificEpithet and infraspecificEpithet

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:36Z]

The last 3 errors (comment 2 & 3) are true for all hybrid formulas:
- Extra space at the end
- The whole hybrid formula is italic
- Missing specificEpithet (and infraspecificEpithet)

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-03-07 14:36Z]

Here's some details:
-The space is added before the author name, since taxa 8175,7490 and 4748 don't have any authors, the space is left there. We should just trim the name.
-The italic rule is applied like this for taxon 7490: 
fullScientificName = "<em>" + uninomial + " " + binomial + "</em> var. <em>" + trinomial + "</em> " + authority;
Since trinomial is "canadensis × Calamagrostis canadensis var. pickeringii", the result is accurate according to the code. If this is not correct, we should just refine the rule.
-specificEpithet and infraspecificEpithet are now there, you need to generate the database to have them in the lookup.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-07 16:11Z]

The name should be trimmed: it affects the data. Once done, this issue can be closed.

The problem with the italic rule is of low priority and recorded in the new issue 1213.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-15 01:09Z]

Names are trimmed.
