### ISSUE TITLE
Pedicularis révisé à partir du manuscrit FNA : noms vernaculaires à réviser EN et FR

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#409]
[Originally posted on GoogleCode (id 1816) on 2013-07-23]

Marc et Marilyn:

Vous trouverez ci-attaché le FNA ms de Pedicularis. J'ai fait d'importantes révisions à la taxonomie et changé les vernaculaires de place en accord à cela.

Il faut cependant tout réviser et fournir des noms là où ils manquent.

Marilyn: the ms provides sources for some names you have for these taxa that have no source currently.

Bonnes vacances si vous y êtes!

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-07-24 21:09Z]

Done as far as French names are concerned.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-28 14:36Z]

Got through almost all the English vernaculars except P. sudetica ssp arctoeuropaea. Just wondering what folks think is best for this subspecies?
Would 'circumpolar lousewort' or 'polar lousewort' or 'high arctic lousewort' be suitable? It's not just arctic Europe.
Here's the link for the PanArctic text http://nhm2.uio.no/paf/810713 
Also any ideas for P. sudetica ssp. interior? other than Kershaw's name as 'purple rattle?
Any ideas to help on these 2 subspecies would be great!
Luc - in the FNA manuscript, I don't know if you want to mention to the author that Langsdorff's name has two 'f's.
Also manuscript has 'red rattle' in 2 different formats. One word 'redrattle' with P. flammea, and two words 'red rattle' with P. sylvatica. Also English vernaculars for these two species could be improved instead of the same name for both species.
thanks for the manuscripts, this is so helpful!

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-08-23 21:00Z]

Marilyn,

Of course, Pedicularis sudetica subsp. arctoeuropaea is not restricted to Arctic Europe, but I would not think that this makes the name a misnomer. The taxon has presumably been described from that part of the world, even though it is now reported from elsewhere. I prefer to keep close to the Latin name, if there is no ambiguity and if the name is not clearly the result of an error.

Concerning subsp. interior, the French name « pédiculaire à bractées dilatées » was chosen by botanists who know the taxon and were working on its designation as vulnerable in Quebec. It refers to the bracts, which are presumably « enlarged ».

Hope this is useful.

Marc
