### ISSUE TITLE
Isoetes xechtuckerii : erroneous vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#427]
[Originally posted on GoogleCode (id 1889) on 2013-10-09]

MArc and Marilyn:

Below is the comment by Mike Oldham concerning the vernaculars given this hybrid taxon. They are, obviously, erroneous.

&quot;The English common name of this hybrid was coined by its describers (Brunton &amp; Britton 1999) to reflect its parentage (i.e. ECHinospora X TUCKERmanii) rather than to commemorate someone named &quot;Echtucker&quot;.&quot;

I guess he means the Latin name, but the original paper could be checked.

Need new vernaculars if we want to bother. At least, the current ones should be removed.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 23:33Z]

I'm really glad that Mike alerted to this situation. I removed the erroneous English vernacular of "Echtucker's quillwort" and placed the taxon only with the English vernacular of "hybrid quillwort". The original paper doesn't provide any suggestions.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-04 15:33Z]

Marc, you need to review/fix the French vernacular, based upon Mike's comment, then list this issue as finished please
(I added your email so you will see this one)

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-06 13:44Z]

I deleted this horrific French name. In fact, I do not know why I bothered introducing it in the first place, since this is a hybrid. I must have been in a strange mood.
I now notice that other Isoetes hybrids have been given French names by Alain Cuerrier or by myself. However, these can remain, since they do not create any problem.

Marilyn, don't you think "hybrid quillwort" is a bit unspecific, since there are several hybrid Isoetes in the database? Your decision, of course.

**Comment by manions** [comment]
Hi Marc
I spent lots of time on this one previously, plus did another review this morning. I can't find anything that might be suitable as an English vernacular for this hybrid. It's the only 'hybrid quillwort' currently listed with the VASCAN database (all of the others I did find a vernacular), so that generic name will have to do for now.
I'll close this issue.
