### ISSUE TITLE
not native to insular Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#519]
[Originally posted on GoogleCode (id 86) on 2010-12-17]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7167

<b>What data are incorrect or missing?</b>
Larix decidua is listed as native to Nfld.

<b>What data are you expecting instead?</b>
Larix decidua is planted, often in plantations, in Nfld, but is not native to the island.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-17 13:48Z]

Labeled as introduced in original database. This may be an importation problem.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-31 13:42Z]

Larix decidua is correctly shown as introduced in Nfld: http://data.canadensys.net/vascan/taxon/7164

Since this is a rather old issue and the taxon id has changed (7167 → 7164), I assume this was an earlier - incorrect - version of the database.
