### ISSUE TITLE
Larix kaempferi not native in NF or ON

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#520]
[Originally posted on GoogleCode (id 87) on 2010-12-17]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7168

<b>What data are incorrect or missing?</b>
Larix kaempferi is listed as native in Nfld.

<b>What data are you expecting instead?</b>
Larix kaempferi is introduced in Nfld., and also Ontario, not native.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-17 13:48Z]

Labeled as introduced in original database. This may be an importation problem.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-31 13:44Z]

Larix kaempferi is correctly shown as introduced in Nfld and ON: http://data.canadensys.net/vascan/taxon/7165

Since this is a rather old issue and the taxon id has changed (7168 → 7165), I assume this was an earlier - incorrect - version of the database.
