### ISSUE TITLE
authority of varietal combination

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#521]
[Originally posted on GoogleCode (id 88) on 2010-12-17]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2770

<b>What data are incorrect or missing?</b>
Achillea lanulosa var. megacephala (Raup) 9 [no name given]

<b>What data are you expecting instead?</b>
I've seen Achillea lanulosa Nutt. subsp. megacephala (Raup) Argus in ITIS, 
and A. millefolium var. megacephala (Raup) B.Boivin,
but can't find the author online of A. lanulosa var megacephala 

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-20 16:39Z]

There has been no combination done of this variety under Achillea lanulosa, which is why there is no authority provided. No one has done the necessary taxonomic work. It was not treated in FNA19 (nor would it have been treated properly there, given the taxonomy presented). But as the taxon is of conservation concern in Canada and it was impossible to ignore it, therefore it is listed currently in this slightly incorrect form. It will remain so until the combination is made.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-31 13:50Z]

In the database we currently only have one Achillea taxon with "megacephala" in the name:

Achillea millefolium subsp. lanulosa var. megacephala (Raup) B. Boivin
http://data.canadensys.net/vascan/taxon/2767

"Achillea lanulosa var. megacephala (Raup) 9 [no name given]" seems to be removed. Is this issue solved?

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-08-31 13:56Z]

Yes, it was just the typo '9' in place of B. Boivin that I had commented on.  - Sue

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-12 15:16Z]

Issue 455 has been merged into this issue.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-08 01:11Z]

Luc, this issue seems to be resolved. Can you close it?
