### ISSUE TITLE
missing parentheses in front of parenthetical author of species.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#639]
[Originally posted on GoogleCode (id 217) on 2011-02-10]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9870

<b>What data are incorrect or missing?</b>
Pinguicula vulgaris subsp. macroceras Pallas ex Link) Calder &amp; Roy L. Taylor

<b>What data are you expecting instead?</b>
Pinguicula vulgaris subsp. macroceras (Pallas ex Link) Calder &amp; Roy L. Taylor

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-11 13:47Z]

Already fixed in database. Numerous small errors were fixed in global checks. These have not been published yet. They will be with the last upload before a fully functional VASCAN (including the back end, which is now ready).

Thanks for signaling it nonetheless.
