### ISSUE TITLE
hybrid parents

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#663]
[Originally posted on GoogleCode (id 242) on 2011-03-01]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6407

<b>What data are incorrect or missing?</b>
Mentha aquatica x Mentha spicata

<b>What data are you expecting instead?</b>
Mentha aquatica x Mentha longifolia
[M. aquatica x M. spicata are the hybrids parents of M. x piperita.

<b>If applicable, please provide an authoritative source.</b>
GRIN, TelaBotanica have longifolia as one of the authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 13:24Z]

Since one of the parents is not in VASCAN (and I would have to exclude it from CAnada, without source, if I were to add it), I am removing the offending parent and leaving a blank for the second.
We have not found a good mechanism to add name without having to deal with them in the main list.
