### ISSUE TITLE
authorities of synonyms & species name; Q about subsp. cannabinum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#777]
[Originally posted on GoogleCode (id 362) on 2011-04-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2661

<b>What data are incorrect or missing?</b>
Apocynum cannabinum var. hypericifolium A. Gray
Apocynum sibiricum var. glaberrimum A. de Candolle

<b>What data are you expecting instead?</b>
Apocynum cannabinum var. hypericifolium (Aiton) A. Gray
Apocynum cannabinum var. glaberrimum A. de Candolle

<b>If applicable, please provide an authoritative source.</b>
Tropicos; Neither Tropicos nor IPNI list the combination 
Apocynum sibiricum  var. glaberrimum.

Also, Scoggan lists var. cannabinum as occurring in southern Ontario. Was Boivin's specimen a misID?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-04 13:13Z]

I am querying Bill Crins and Mike Oldham on this issue. As you saw, I cannot interpret what FOIBIS did.
Fixed the other issues.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 19:38Z]

After querying, neither can point to a specific answer. They had largely ignored the problem.
However, attached is a paper provided by Mike that shows the issue is difficult and certainly not resolved there, particularly as the var. was reported only from Ont. in Scoggan.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-06-30 13:36Z]

TROPICOS and IPNI now list var. glaberrimum

I am adding var. cannabinum as uncertain in Ont.for the time being, since it is reported in the lit. by Scoggan, at least. Do not know for other provinces
The work of DiTommaso et al does not facilitates a decision because they mixed var. cannabinum specimens and uncertain ones on their map - which does not help in deciding where the taxon might be in Canada
