### ISSUE TITLE
a few typos in synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#810]
[Originally posted on GoogleCode (id 395) on 2011-04-28]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3681

<b>What data are incorrect or missing?</b>
Alnus alnovetula var. crispa (Aiton) H.J.P. Winkler
Alnus crispa var. mollis (Fernald) Ferna
Alnus crispa var. stragula Fernald
Alnus viridis var. crispa (Michaux) House

<b>What data are you expecting instead?</b>
Alnus alnobetula var. crispa (Dryander ex Aiton) H.J.P. Winkler {note spelling correction in alnoBetula, not alnoVetula)
Alnus crispa var. mollis (Fernald) Fernald
Alnus crispa forma stragula Fernald
Alnus viridis var. crispa (Dryander ex Aiton) House

<b>If applicable, please provide an authoritative source.</b>
Tropicos &amp; IPNI; Tropicos has both var. and forma strangula, but provides no lit citation for var. strangula; IPNI has only forma, which is how Fernald published it.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-29 13:27Z]

I removed var. stragula but FNA 3 had it - but the nomenclature editor of the time was less thorough - may have been added to TROPICOS on the basis of FNA 

forma are not included in VASCAN, so the name is not being edited

a note about authors associated with Aiton: none of them can be cited due to the technicality that Aiton, the bugger, never attributed the names to them, though it is clear from other data that they did these names - TROPICOS err in this - Solander is another victim of this
I corrected the authority of the accepted subsp....

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-04-29 14:47Z]

Hi Luc,

So, I should drop Dryander from the Dryander ex Aiton, and just leave these (and similar situations) as Aiton?  Makes for shorter names, but your right, it short changes the actual authors.  Too bad.  - Sue

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-29 15:33Z]

Yes, that is the situation.
TROPICOS has not corrected all these.
Luc
