### ISSUE TITLE
question about species authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#835]
[Originally posted on GoogleCode (id 435) on 2011-05-11]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2742

<b>What data are incorrect or missing?</b>
Muscari armeniacum Baker

<b>What data are you expecting instead?</b>
? Muscari armeniacum Leichtlin ex Baker

<b>If applicable, please provide an authoritative source.</b>
GRIN has Leichtlin ex Baker; Tropicos has Baker; IPNI has both.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-28 17:43Z]

In IPNI-IK the following is added: "I received it first in 1876 from Max Leichtlin, Esq., and have since had it from Mr. Elwes, and studied it last year in the living state in the Kew collection."
There is nothing that indicates Leichtlin created the name, just that he provided the plants. 
However, Index synonymique also has Leichtlin - for now I will add it but it is not a closed issue, I guess.
