### ISSUE TITLE
placement of synonyms under wrong species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#930]
[Originally posted on GoogleCode (id 571) on 2011-07-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5582

<b>What data are incorrect or missing?</b>
Vaccinium microphyllum (Lange) Hagerup
Vaccinium uliginosum subsp. microphyllum Lange

<b>What data are you expecting instead?</b>
there are 4 combinations using microphyllum/-us (Lange) listed under V. oxycoccos:
http://data.canadensys.net/vascan/taxon/5577
Shouldn't all combinations of the same basionym be synonymous with the same species?

<b>If applicable, please provide an authoritative source.</b>
FNA has them all synonymous under V. oxycoccos, not V. uliginosum

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-07 18:58Z]

This seems more tangled than it looks at firt sight. There are many microphyllum, two illeg., and people may have tangled the authorities. I cannot sort it out immediately.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-27 13:50Z]

It is not because an epiteth is identical and by the same author that it necessarily was not combined with different entities. In this case, microphyllum associated with uliginosum and with palustris are based on different types

the name V. microphyllum (Lange) etc. is illeg. however, which was added
